@echo off
setlocal EnableDelayedExpansion
ENDLOCAL

IF NOT "%PDFtoPDF_DEFAULTS%"=="OK" (
	echo Impostazioni predefinite mancanti!
	pause
	goto END
)

SET PDFtoPDF_VER=PDFtoPDF
GOTO AFTER_SWITCH
:SWITCH
cls
IF "%PDFtoPDF_VER%"=="PDFtoPDF" (SET PDFtoPDF_VER=PDFtoPDF2) ELSE (SET PDFtoPDF_VER=PDFtoPDF)
:AFTER_SWITCH

IF "%PDFtoPDF_VER%"=="PDFtoPDF2" (
	echo ----------------------------------------------
	echo ---------------- VERSIONE 2.0 ----------------
	echo ----------------------------------------------
) ELSE (
	echo ----------------------------------------------
	echo ---------------- VERSIONE 3.0 ----------------
	echo ----------------------------------------------
)
echo  T - Trasforma le pagine in Immagini [ORIGINALI]-^>[TRASFORMATI]
echo  S - Dividi Massivamente ad intervallo di pagine [ORIGINALI]-^>[DIVISI]
echo  V - Imposta in VERTICALE tutte le pagine e Foglio A4 [ORIZZONTALI]-^>[VERTICALI]
echo  U - Unisci Lettera e Pagamento [LETTERE][PAGAMENTI]-^>[ATTI]
echo  B - Crea Bozza/PreStampa PDF [ATTI]-^>[ELABORAZIONE]
echo  Q - Crea Bozza/PreStampa e Stampa OCT+PDF [ATTI]-^>[OCT+ELABORAZIONE]
echo  O - Stampa su File OCT+PDF [ELABORAZIONE]-^>[OCT]
echo  F - Stampa su File PDF [ELABORAZIONE]-^>[STAMPE]
echo  C - Stampa su Canon 6160 [ELABORAZIONE]-^>*STAMPA REALE SU CARTA*
echo  R - Stampa su Ricoh 9002 [ELABORAZIONE]-^>*STAMPA REALE SU CARTA*
echo  G - Inserisci Pagina con dati da Griglia [ATTI]-^>[ATTI_ORIGINALI][ATTI]
echo  P - Inserisci Pagine da file PDF [ATTI]-^>[ATTI_ORIGINALI][ATTI]
echo  A - Aggiungi Pagine VUOTE [ATTI]-^>[ATTI_ORIGINALI][ATTI]
echo  I - Crea Griglia da Indirizzi [ATTI]-^>[EXPORT.CSV]
echo  D - Riduci Dimensioni Immagini [ATTI]-^>[ATTI_ORIGINALI][ATTI]
echo  M - Merge/Unione OCT [*/OCT.7z]-^>[UnioneOCT/OCT]
echo  0 - Conteggio [ATTI]
echo  1 - Crea Bollettini 123 da griglia []-^>[]
echo  4 - Crea Bollettini 451 da griglia []-^>[]
echo  8 - Crea Bollettini 896 da griglia []-^>[]
echo  2 - Crea F24 da griglia [...]-^>[F24]
echo  W - SWITCH VERSIONE
echo  E - ESCI
echo  N.B. PER LA POSTA TIME NON AGGIUNGERE LA COVER USANDO LA "G" MA RICORDATI DI IMPOSTARE A 1 LA FUNZIONE "COVER INDIRIZZO"
echo ----------------------------------------------
echo.
choice /C UBFCRGPVI01482ADTSOQMEW
SET CHOICE=%ERRORLEVEL%
SET "MULTIPLE_MODE="
IF "%CHOICE%"=="1" SET CHOICE_TEXT=UNION
IF "%CHOICE%"=="2" SET CHOICE_TEXT=PRINT
IF "%CHOICE%"=="3" SET CHOICE_TEXT=PRINT
IF "%CHOICE%"=="4" SET CHOICE_TEXT=PRINT
IF "%CHOICE%"=="5" SET CHOICE_TEXT=PRINT
IF "%CHOICE%"=="6" SET CHOICE_TEXT=BYXLS
IF "%CHOICE%"=="7" SET CHOICE_TEXT=BYPDF
IF "%CHOICE%"=="8" SET CHOICE_TEXT=VERTI
IF "%CHOICE%"=="9" SET CHOICE_TEXT=EXPRT
IF "%CHOICE%"=="10" SET CHOICE_TEXT=COUNT
IF "%CHOICE%"=="11" SET CHOICE_TEXT=123PG
IF "%CHOICE%"=="12" SET CHOICE_TEXT=451PG
IF "%CHOICE%"=="13" SET CHOICE_TEXT=896PG
IF "%CHOICE%"=="14" SET CHOICE_TEXT=F24PG
IF "%CHOICE%"=="15" SET CHOICE_TEXT=BYBLK
IF "%CHOICE%"=="16" SET CHOICE_TEXT=BWRES
IF "%CHOICE%"=="17" SET CHOICE_TEXT=TRANS
IF "%CHOICE%"=="18" SET CHOICE_TEXT=SPLIT
IF "%CHOICE%"=="19" SET CHOICE_TEXT=PRINT
IF "%CHOICE%"=="20" SET CHOICE_TEXT=PRINT
IF "%CHOICE%"=="21" SET CHOICE_TEXT=ONION

IF "%CHOICE%"=="1" SET PRINTER_TEXT=ELAB
IF "%CHOICE%"=="2" SET PRINTER_TEXT=PREP
IF "%CHOICE%"=="3" SET PRINTER_TEXT=FILE
IF "%CHOICE%"=="4" SET PRINTER_TEXT=CANO
IF "%CHOICE%"=="5" SET PRINTER_TEXT=RICO
IF "%CHOICE%"=="6" SET PRINTER_TEXT=ELAB
IF "%CHOICE%"=="7" SET PRINTER_TEXT=ELAB
IF "%CHOICE%"=="8" SET PRINTER_TEXT=ELAB
IF "%CHOICE%"=="9" SET PRINTER_TEXT=ELAB
IF "%CHOICE%"=="10" SET PRINTER_TEXT=ELAB
IF "%CHOICE%"=="11" SET PRINTER_TEXT=ELAB
IF "%CHOICE%"=="12" SET PRINTER_TEXT=ELAB
IF "%CHOICE%"=="13" SET PRINTER_TEXT=ELAB
IF "%CHOICE%"=="14" SET PRINTER_TEXT=ELAB
IF "%CHOICE%"=="15" SET PRINTER_TEXT=ELAB
IF "%CHOICE%"=="16" SET PRINTER_TEXT=ELAB
IF "%CHOICE%"=="17" SET PRINTER_TEXT=ELAB
IF "%CHOICE%"=="18" SET PRINTER_TEXT=ELAB
IF "%CHOICE%"=="19" SET PRINTER_TEXT=OCTS
IF "%CHOICE%"=="20" SET PRINTER_TEXT=OCTS
IF "%CHOICE%"=="20" SET MULTIPLE_MODE=OCTP
IF "%CHOICE%"=="21" SET PRINTER_TEXT=ELAB

IF "%CHOICE%"=="22" GOTO END
IF "%CHOICE%"=="23" GOTO SWITCH
:PAGES
IF "%CHOICE%"=="18" SET /p PAGES="Inserisci Intervallo di Pagine: "
IF "%CHOICE%"=="18" echo %PAGES%| findstr /r "^[0-9]*$">nul
IF "%CHOICE%"=="18" IF NOT "%ERRORLEVEL%"=="0" (
	echo Non hai inserito un numero valido!
	GOTO PAGES
)
SET "ZOOM_S_DATAMATRIX=180"
SET "ZOOM_S_DATAMATRIX_PM=144"

SET /a RECT_X_INDZ_LUNG=%RECT_X_INDZ%+%RECT_W_INDZ%-%LONG_W_INDZ%
SET /a RECT_Y_INDZ_LUNG=%RECT_Y_INDZ%+0
SET /a RECT_W_INDZ_LUNG=%LONG_W_INDZ%+0
SET /a RECT_H_INDZ_LUNG=%RECT_H_INDZ%+0

IF "%GENERA_BARCODE%"=="AR" SET /a POSZ_X_BARCODE_T1=%POSZ_X_BARCODE%-7
IF "%GENERA_BARCODE%"=="AR" SET /a POSZ_Y_BARCODE_T1=%POSZ_Y_BARCODE%+1
IF "%GENERA_BARCODE%"=="AR" SET /a POSZ_X_BARCODE_T2=%POSZ_X_BARCODE%-5
IF "%GENERA_BARCODE%"=="AR" SET /a POSZ_Y_BARCODE_T2=%POSZ_Y_BARCODE%+1
IF "%GENERA_BARCODE%"=="AR" SET /a POSZ_X_BARCODE_T3=%POSZ_X_BARCODE%-8
IF "%GENERA_BARCODE%"=="AR" SET /a POSZ_Y_BARCODE_T3=%POSZ_Y_BARCODE%+18

IF "%GENERA_BARCODE%"=="AG" SET /a POSZ_X_BARCODE_T1=%POSZ_X_BARCODE%-12
IF "%GENERA_BARCODE%"=="AG" SET /a POSZ_Y_BARCODE_T1=%POSZ_Y_BARCODE%+10

IF "%GENERA_BARCODE%"=="AM" SET /a POSZ_X_BARCODE_T1=%POSZ_X_BARCODE%-15
IF "%GENERA_BARCODE%"=="AM" SET /a POSZ_Y_BARCODE_T1=%POSZ_Y_BARCODE%+10
IF "%GENERA_BARCODE%"=="AM" SET /a POSZ_X_BARCODE_T2=%POSZ_X_BARCODE%-6
IF "%GENERA_BARCODE%"=="AM" SET /a POSZ_Y_BARCODE_T2=%POSZ_Y_BARCODE%+6

IF "%GENERA_BARCODE%"=="RK" SET /a POSZ_X_BARCODE_T1=%POSZ_X_BARCODE%-12
IF "%GENERA_BARCODE%"=="RK" SET /a POSZ_Y_BARCODE_T1=%POSZ_Y_BARCODE%+10

IF "%GENERA_BARCODE%"=="RG" SET /a POSZ_X_BARCODE_T1=%POSZ_X_BARCODE%-3
IF "%GENERA_BARCODE%"=="RG" SET /a POSZ_Y_BARCODE_T1=%POSZ_Y_BARCODE%+8
IF "%GENERA_BARCODE%"=="RG" SET /a POSZ_X_BARCODE_T2=%POSZ_X_BARCODE%-5
IF "%GENERA_BARCODE%"=="RG" SET /a POSZ_Y_BARCODE_T2=%POSZ_Y_BARCODE%-2

SET OFFSET_BARCODE_TE=-9
SET /a POSZ_X_BARCODE_TE0=%POSZ_X_BARCODE%+%OFFSET_BARCODE_TE%
SET /a POSZ_Y_BARCODE_TE0=%POSZ_Y_BARCODE%
SET /a POSZ_X_BARCODE_TE1=%POSZ_X_BARCODE%-11+%OFFSET_BARCODE_TE%
SET /a POSZ_Y_BARCODE_TE1=%POSZ_Y_BARCODE%+4
SET /a POSZ_X_BARCODE_TE2=%POSZ_X_BARCODE%-9+%OFFSET_BARCODE_TE%
SET /a POSZ_Y_BARCODE_TE2=%POSZ_Y_BARCODE%+2
SET /a POSZ_X_BARCODE_TE3=%POSZ_X_BARCODE%-8+%OFFSET_BARCODE_TE%
SET /a POSZ_Y_BARCODE_TE3=%POSZ_Y_BARCODE%+9

rem SET /a POSZ_X_OMRS_R1=%POSZ_X_OMRS%-2
rem SET /a POSZ_Y_OMRS_R1=%POSZ_Y_OMRS%-2

IF "%MATCH_FIND_B_WORD%"=="" SET "MATCH_FIND_B_WORD=%MATCH_FIND_B_LETT%"
IF "%MATCH_FIND_E_WORD%"=="" SET "MATCH_FIND_E_WORD=%MATCH_FIND_E_LETT%"
IF "%MATCH_FIND_A_WORD%"=="" SET "MATCH_FIND_A_WORD=%MATCH_FIND_A_LETT%"
SET "MATCH_SEARCH_WORD=%MATCH_FIND_B_WORD%%MATCH_FIND_E_WORD%%MATCH_FIND_A_WORD%"

IF "%MATCH_FIND_B_AUTH%"=="" SET "MATCH_FIND_B_AUTH=%MATCH_FIND_B_LETT%"
IF "%MATCH_FIND_E_AUTH%"=="" SET "MATCH_FIND_E_AUTH=%MATCH_FIND_E_LETT%"
IF "%MATCH_FIND_A_AUTH%"=="" SET "MATCH_FIND_A_AUTH=%MATCH_FIND_A_LETT%"
SET "MATCH_SEARCH_AUTH=%MATCH_FIND_B_AUTH%%MATCH_FIND_E_AUTH%%MATCH_FIND_A_AUTH%"

IF "%FIND_B_WORD%"=="" SET "FIND_B_WORD=%FIND_B_LETT%"
IF "%FIND_E_WORD%"=="" SET "FIND_E_WORD=%FIND_E_LETT%"
IF "%FIND_A_WORD%"=="" SET "FIND_A_WORD=%FIND_A_LETT%"
SET "SEARCH_WORD=%FIND_B_WORD%(%FIND_E_WORD%)%FIND_A_WORD%"

IF "%FIND_B_AUTH%"=="" SET "FIND_B_AUTH=%FIND_B_LETT%"
IF "%FIND_E_AUTH%"=="" SET "FIND_E_AUTH=%FIND_E_LETT%"
IF "%FIND_A_AUTH%"=="" SET "FIND_A_AUTH=%FIND_A_LETT%"
SET "SEARCH_AUTH=%FIND_B_AUTH%(%FIND_E_AUTH%)%FIND_A_AUTH%"

SET "MATCH_SEARCH_LETT=%MATCH_FIND_B_LETT%%MATCH_FIND_E_LETT%%MATCH_FIND_A_LETT%"
SET "MATCH_SEARCH_PAGA=%MATCH_FIND_B_PAGA%%MATCH_FIND_E_PAGA%%MATCH_FIND_A_PAGA%"
SET "MATCH_SEARCH_CONV=%MATCH_FIND_B_CONV%%MATCH_FIND_E_CONV%%MATCH_FIND_A_CONV%"
SET "SEARCH_PAGE=%FIND_B_PAGE%(%FIND_E_PAGE%)%FIND_A_PAGE%"
SET "SEARCH_LETT=%FIND_B_LETT%(%FIND_E_LETT%)%FIND_A_LETT%"
SET "SEARCH_CODE=%FIND_B_CODE%(%FIND_E_CODE%)%FIND_A_CODE%"
SET "SEARCH_GRIDTEXT=%FIND_B_GRIDTEXT%(%FIND_E_GRIDTEXT%)%FIND_A_GRIDTEXT%"
SET "SEARCH_BARCODETEXT=%FIND_B_BARCODETEXT%(%FIND_E_BARCODETEXT%)%FIND_A_BARCODETEXT%"
SET "SEARCH_GRIDADDRESS=%FIND_B_GRIDADDRESS%(%FIND_E_GRIDADDRESS%)%FIND_A_GRIDADDRESS%"
SET "SEARCH_PAGA=%FIND_B_PAGA%(%FIND_E_PAGA%)%FIND_A_PAGA%"
SET "SEARCH_CONV=%FIND_B_CONV%(%FIND_E_CONV%)%FIND_A_CONV%"
SET "SEARCH_INDZ=%FIND_B_INDZ%(%FIND_E_INDZ%)%FIND_A_INDZ%"
SET "SEARCH_TEXT=%FIND_B_TEXT%(%FIND_E_TEXT%)%FIND_A_TEXT%"
SET "SEARCH_ZONE=%FIND_B_ZONE%(%FIND_E_ZONE%)%FIND_A_ZONE%"
SET "SEARCH_OMRS=%FIND_B_OMRS%(%FIND_E_OMRS%)%FIND_A_OMRS%"
SET "SEARCH_OMRP=%FIND_B_OMRP%%FIND_E_OMRP%%FIND_A_OMRP%"
SET "SEARCH_LETT=%FIND_B_LETT%(%FIND_E_LETT%)%FIND_A_LETT%"
SET "SEARCH_FPDF=%FIND_B_FPDF%(%FIND_E_FPDF%)%FIND_A_FPDF%"
SET "SEARCH_BLNK=%FIND_B_BLNK%(%FIND_E_BLNK%)%FIND_A_BLNK%"
SET "SEARCH_FXLS=%FIND_B_FXLS%(%FIND_E_FXLS%)%FIND_A_FXLS%"
SET "SEARCH_VOID=%FIND_B_VOID%(%FIND_E_VOID%)%FIND_A_VOID%"
SET "SEARCH_SKIP=%FIND_B_SKIP%(%FIND_E_SKIP%)%FIND_A_SKIP%"
SET "SEARCH_IMAG=%FIND_B_IMAG%%FIND_E_IMAG%%FIND_A_IMAG%"
SET "SEARCH_DUPLEX_A=%FIND_B_DUPLEX_A%(%FIND_E_DUPLEX_A%)%FIND_A_DUPLEX_A%"
SET "SEARCH_DUPLEX_B=%FIND_B_DUPLEX_B%(%FIND_E_DUPLEX_B%)%FIND_A_DUPLEX_B%"
SET "SEARCH_DUPLEX_C=%FIND_B_DUPLEX_C%(%FIND_E_DUPLEX_C%)%FIND_A_DUPLEX_C%"
SET "SEARCH_DUPLEX_D=%FIND_B_DUPLEX_D%(%FIND_E_DUPLEX_D%)%FIND_A_DUPLEX_D%"


IF "%RECT_X_AUTH%"=="" SET "RECT_X_AUTH=%RECT_X_LETT%"
IF "%RECT_Y_AUTH%"=="" SET "RECT_Y_AUTH=%RECT_Y_LETT%"
IF "%RECT_W_AUTH%"=="" SET "RECT_W_AUTH=%RECT_W_LETT%"
IF "%RECT_H_AUTH%"=="" SET "RECT_H_AUTH=%RECT_H_LETT%"
SET RECT_AUTH=%RECT_X_AUTH%::%RECT_Y_AUTH%::%RECT_W_AUTH%::%RECT_H_AUTH%

IF "%MATCH_RECT_X_AUTH%"=="" SET "MATCH_RECT_X_AUTH=%MATCH_RECT_X_LETT%"
IF "%MATCH_RECT_Y_AUTH%"=="" SET "MATCH_RECT_Y_AUTH=%MATCH_RECT_Y_LETT%"
IF "%MATCH_RECT_W_AUTH%"=="" SET "MATCH_RECT_W_AUTH=%MATCH_RECT_W_LETT%"
IF "%MATCH_RECT_H_AUTH%"=="" SET "MATCH_RECT_H_AUTH=%MATCH_RECT_H_LETT%"
SET MATCH_RECT_AUTH=%MATCH_RECT_X_AUTH%::%MATCH_RECT_Y_AUTH%::%MATCH_RECT_W_AUTH%::%MATCH_RECT_H_AUTH%

IF "%RECT_X_WORD%"=="" SET "RECT_X_WORD=%RECT_X_LETT%"
IF "%RECT_Y_WORD%"=="" SET "RECT_Y_WORD=%RECT_Y_LETT%"
IF "%RECT_W_WORD%"=="" SET "RECT_W_WORD=%RECT_W_LETT%"
IF "%RECT_H_WORD%"=="" SET "RECT_H_WORD=%RECT_H_LETT%"
SET RECT_WORD=%RECT_X_WORD%::%RECT_Y_WORD%::%RECT_W_WORD%::%RECT_H_WORD%

IF "%MATCH_RECT_X_WORD%"=="" SET "MATCH_RECT_X_WORD=%MATCH_RECT_X_LETT%"
IF "%MATCH_RECT_Y_WORD%"=="" SET "MATCH_RECT_Y_WORD=%MATCH_RECT_Y_LETT%"
IF "%MATCH_RECT_W_WORD%"=="" SET "MATCH_RECT_W_WORD=%MATCH_RECT_W_LETT%"
IF "%MATCH_RECT_H_WORD%"=="" SET "MATCH_RECT_H_WORD=%MATCH_RECT_H_LETT%"
SET MATCH_RECT_WORD=%MATCH_RECT_X_WORD%::%MATCH_RECT_Y_WORD%::%MATCH_RECT_W_WORD%::%MATCH_RECT_H_WORD%

SET RECT_PAGE=%RECT_X_PAGE%::%RECT_Y_PAGE%::%RECT_W_PAGE%::%RECT_H_PAGE%
SET MATCH_RECT_LETT=%MATCH_RECT_X_LETT%::%MATCH_RECT_Y_LETT%::%MATCH_RECT_W_LETT%::%MATCH_RECT_H_LETT%
SET MATCH_RECT_PAGA=%MATCH_RECT_X_PAGA%::%MATCH_RECT_Y_PAGA%::%MATCH_RECT_W_PAGA%::%MATCH_RECT_H_PAGA%
SET MATCH_RECT_CONV=%MATCH_RECT_X_CONV%::%MATCH_RECT_Y_CONV%::%MATCH_RECT_W_CONV%::%MATCH_RECT_H_CONV%
SET RECT_LETT=%RECT_X_LETT%::%RECT_Y_LETT%::%RECT_W_LETT%::%RECT_H_LETT%
SET RECT_CODE=%RECT_X_CODE%::%RECT_Y_CODE%::%RECT_W_CODE%::%RECT_H_CODE%
SET RECT_GRIDTEXT=%RECT_X_GRIDTEXT%::%RECT_Y_GRIDTEXT%::%RECT_W_GRIDTEXT%::%RECT_H_GRIDTEXT%
SET RECT_BARCODETEXT=%RECT_X_BARCODETEXT%::%RECT_Y_BARCODETEXT%::%RECT_W_BARCODETEXT%::%RECT_H_BARCODETEXT%
SET RECT_GRIDADDRESS=%RECT_X_GRIDADDRESS%::%RECT_Y_GRIDADDRESS%::%RECT_W_GRIDADDRESS%::%RECT_H_GRIDADDRESS%
SET RECT_PAGA=%RECT_X_PAGA%::%RECT_Y_PAGA%::%RECT_W_PAGA%::%RECT_H_PAGA%
SET RECT_CONV=%RECT_X_CONV%::%RECT_Y_CONV%::%RECT_W_CONV%::%RECT_H_CONV%
SET RECT_INDZ=%RECT_X_INDZ%::%RECT_Y_INDZ%::%RECT_W_INDZ%::%RECT_H_INDZ%
SET RECT_TEXT=%RECT_X_TEXT%::%RECT_Y_TEXT%::%RECT_W_TEXT%::%RECT_H_TEXT%
SET RECT_ZONE=%RECT_X_ZONE%::%RECT_Y_ZONE%::%RECT_W_ZONE%::%RECT_H_ZONE%
SET RECT_OMRP=%RECT_X_OMRP%::%RECT_Y_OMRP%::%RECT_W_OMRP%::%RECT_H_OMRP%
SET RECT_OMRS=%RECT_X_OMRS%::%RECT_Y_OMRS%::%RECT_W_OMRS%::%RECT_H_OMRS%
SET RECT_FXLS=%RECT_X_FXLS%::%RECT_Y_FXLS%::%RECT_W_FXLS%::%RECT_H_FXLS%
SET RECT_FPDF=%RECT_X_FPDF%::%RECT_Y_FPDF%::%RECT_W_FPDF%::%RECT_H_FPDF%
SET RECT_BLNK=%RECT_X_BLNK%::%RECT_Y_BLNK%::%RECT_W_BLNK%::%RECT_H_BLNK%
SET RECT_VOID=%RECT_X_VOID%::%RECT_Y_VOID%::%RECT_W_VOID%::%RECT_H_VOID%
SET RECT_SKIP=%RECT_X_SKIP%::%RECT_Y_SKIP%::%RECT_W_SKIP%::%RECT_H_SKIP%
SET RECT_IMAG=%RECT_X_IMAG%::%RECT_Y_IMAG%::%RECT_W_IMAG%::%RECT_H_IMAG%
SET RECT_INDZ_LUNG=%RECT_X_INDZ_LUNG%::%RECT_Y_INDZ_LUNG%::%RECT_W_INDZ_LUNG%::%RECT_H_INDZ_LUNG%
SET RECT_DUPLEX_A=%RECT_X_DUPLEX_A%::%RECT_Y_DUPLEX_A%::%RECT_W_DUPLEX_A%::%RECT_H_DUPLEX_A%
SET RECT_DUPLEX_B=%RECT_X_DUPLEX_B%::%RECT_Y_DUPLEX_B%::%RECT_W_DUPLEX_B%::%RECT_H_DUPLEX_B%
SET RECT_DUPLEX_C=%RECT_X_DUPLEX_C%::%RECT_Y_DUPLEX_C%::%RECT_W_DUPLEX_C%::%RECT_H_DUPLEX_C%
SET RECT_DUPLEX_D=%RECT_X_DUPLEX_D%::%RECT_Y_DUPLEX_D%::%RECT_W_DUPLEX_D%::%RECT_H_DUPLEX_D%

SET SEARCH_ALLS=.*
SET RECT_ALLS=0::0::297::297

SET PDFtoPDF_PATH=%PDFtoPDF_VER%.jar
for %%i in (%PDFtoPDF_PATH%) do SET "PDFtoPDF_PATH=%%~dp$PATH:%i"
SET "PDFtoPDF_PATH=%PDFtoPDF_PATH%%PDFtoPDF_VER%.jar"
SET F_TEMPLATE_PATH=%PDFtoPDF_VER%.jar
for %%i in (%F_TEMPLATE_PATH%) do SET "F_TEMPLATE_PATH=%%~dp$PATH:%iF24.pdf"
SET F_PROFILE_PATH=%PDFtoPDF_VER%.jar
for %%i in (%F_PROFILE_PATH%) do SET "F_PROFILE_PATH=%%~dp$PATH:%iF24.cmds"
SET F_RELATA_PATH=%PDFtoPDF_VER%.jar
for %%i in (%F_RELATA_PATH%) do SET "F_RELATA_PATH=%%~dp$PATH:%irelata.png"
SET FONTS_PATH=%PDFtoPDF_VER%.jar
for %%i in (%FONTS_PATH%) do SET "FONTS_PATH=%%~dp$PATH:%ifonts"

SET "PARAMS_REPORT=::reportFile==%~1\REPORT.txt"
SET "PARAMS_LOG=::logFile==%~1\LOG.txt"
SET "PARAMS_ERRORS=::errorFile==%~1\ERRORS.txt"
SET "PARAMS=trim::rect::deleteCmds=1::absolute%PARAMS_REPORT%%PARAMS_ERRORS%"
IF "%GENERA_LOG%"=="1" SET "PARAMS=%PARAMS%%PARAMS_LOG%"
rem SET "PARAMS=%PARAMS%::echo%PARAMS_LOG%"
rem echo "%PARAMS%"

IF "%CHOICE_TEXT%"=="F24PG" SET PARAMS=%PARAMS%::grid==%GRID%::gridUnique==rowIndex::fromTemplate==%F_TEMPLATE_PATH%
IF "%CHOICE_TEXT%"=="PRINT" SET PARAMS=%PARAMS%::grid==%GRID%::gridUnique==%GRID_C_UNIQUE%
IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%PRINT_SIZE%"=="" SET PARAMS=%PARAMS%::printSize==%PRINT_SIZE%
IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%PRINT_POSTSCRIPT_FOLDER%"=="" SET PARAMS=%PARAMS%::printPostScript::PostScriptPrintPath==%~1\%PRINT_POSTSCRIPT_FOLDER%
IF "%CHOICE_TEXT%"=="BYXLS" SET PARAMS=%PARAMS%::grid==%GRID%::gridUnique==%GRID_C_UNIQUE%::gridUniqueMatch==%GRID_M_FXLS%
IF "%GENERA_LOG%"=="1" SET PARAMS=%PARAMS%::echo

IF "%PRINTER_TEXT%"=="CANO" SET PARAMS=%PARAMS%::AprintJobs::dpi==300::printBlockStorage==disk::printBlockSlots==15::printBlockPages==35::printBlockThreads==5
IF "%PRINTER_TEXT%"=="RICO" SET PARAMS=%PARAMS%::AprintJobs::dpi==300::printBlockStorage==disk::printBlockSlots==15::printBlockPages==35::printBlockThreads==5
IF "%PRINTER_TEXT%"=="OCTS" SET PARAMS=%PARAMS%::AprintJobs::dpi==300::printBlockStorage==disk::printBlockSlots==15::printBlockPages==150::printBlockThreads==5
IF "%PRINTER_TEXT%"=="FILE" SET PARAMS=%PARAMS%::AprintJobs::dpi==300
IF "%PRINTER_TEXT%"=="BOZZ" SET PARAMS=%PARAMS%::AprintJobs::dpi==300
IF "%CHOICE_TEXT%"=="UNION" SET PARAMS=%PARAMS%::split::previous::nospaces
IF "%CHOICE_TEXT%"=="TRANS" SET PARAMS=%PARAMS%::toImages::previous::previousCanMatch
IF "%CHOICE_TEXT%"=="SPLIT" SET PARAMS=%PARAMS%::massiveSplit==%PAGES%::readerMode==page

SET "PARAMS=%PARAMS%::fontsSource==%FONTS_PATH%::fontsMap==%FONTS_PATH%\00-FontsMap.json"
SET "PARAMS_PREPRINT=%PARAMS%::mergeAddingMissingFonts"
IF NOT "%MULTIPLE_MODE%"=="OCTP" SET "PARAMS_PREPRINT=%PARAMS_PREPRINT%::useGUI"
SET "PARAMS_PRINT=%PARAMS%::useGUI::modifiedRect::printAddingMissingFonts"
rem ::noPrintPostScript::printPDF::printToDuplex
IF "%PRINTER_TEXT%"=="OCTS" SET PARAMS_PRINT=%PARAMS_PRINT%::printOctFileWithParentName::printOctTickets::printOctPages==8000::printOctDivisibleBy==4::printToDuplex

IF "%CHOICE_TEXT%"=="ONION" SET PARAMS=%PARAMS%::mergeOCT::useGUI::printOctPages==8000

SET "DUPLEX_SCALE="
IF NOT "%SCAL_E_LETT%"=="" SET "DUPLEX_SCALE=adapt||"
SET "SIMPLEX_SCALE="
IF NOT "%SCAL_E_PAGA%"=="" SET "SIMPLEX_SCALE=adapt||"

SET "CODE_SOURCE="
IF NOT "%GRID_C_CODE%"=="" SET "CODE_SOURCE=fromGrid==%GRID_C_CODE%||"

SET "GRIDTEXT_SOURCE="
IF NOT "%GRID_C_GRIDTEXT%"=="" SET "GRIDTEXT_SOURCE=fromGrid==%GRID_C_GRIDTEXT%||"

SET "BARCODETEXT_SOURCE="
IF NOT "%GRID_C_BARCODETEXT%"=="" SET "BARCODETEXT_SOURCE=fromGrid==%GRID_C_BARCODETEXT%||"

SET "GRIDADDRESS_SOURCE="
IF NOT "%GRID_C_GRIDADDRESS%"=="" SET "GRIDADDRESS_SOURCE=fromGridFormat==%GRID_C_GRIDADDRESS%||"

SET "BARCODE_SOURCE="
IF NOT "%GRID_C_BARCODE%"=="" SET "BARCODE_SOURCE=fromGrid==%GRID_C_BARCODE%||"
IF NOT "%GRID_C_BARCODE%"=="" IF "%GENERA_BARCODE%"=="AR" IF "%PRINTER_TEXT%"=="BOZZ" SET "BARCODE_SOURCE=fromText==00000000000-0||"
IF NOT "%GRID_C_BARCODE%"=="" IF "%GENERA_BARCODE%"=="AG" IF "%PRINTER_TEXT%"=="BOZZ" SET "BARCODE_SOURCE=fromText==00000000000-0||"
IF NOT "%GRID_C_BARCODE%"=="" IF "%GENERA_BARCODE%"=="RG" IF "%PRINTER_TEXT%"=="BOZZ" SET "BARCODE_SOURCE=fromText==00000000000-0||"
IF NOT "%GRID_C_BARCODE%"=="" IF "%GENERA_BARCODE%"=="AM" IF "%PRINTER_TEXT%"=="BOZZ" SET "BARCODE_SOURCE=fromText==00000000000-0||"
IF NOT "%GRID_C_BARCODE%"=="" IF "%GENERA_BARCODE%"=="RK" IF "%PRINTER_TEXT%"=="BOZZ" SET "BARCODE_SOURCE=fromText==00000000000-0||"

SET "DATAMATRIX_SOURCE="
IF NOT "%GRID_C_DATAMATRIX%"=="" SET "DATAMATRIX_SOURCE=fromGrid==%GRID_C_DATAMATRIX%||"
IF NOT "%GRID_C_DATAMATRIX%"=="" IF "%GENERA_DATAMATRIX%"=="1" IF "%PRINTER_TEXT%"=="BOZZ" SET "DATAMATRIX_SOURCE=fromText==00000000000-0||"
IF NOT "%GRID_C_DATAMATRIX%"=="" IF "%GENERA_DATAMATRIX%"=="1" IF "%PRINTER_TEXT%"=="BOZZ" SET "DATAMATRIX_SOURCE=fromText==00000000000-0||"

SET "DATAMATRIX_PM_SOURCE="
IF NOT "%GRID_C_DATAMATRIX_PM%"=="" SET "DATAMATRIX_PM_SOURCE=fromGrid==%GRID_C_DATAMATRIX_PM%||"
IF NOT "%GRID_C_DATAMATRIX_PM%"=="" IF "%GENERA_DATAMATRIX_PM%"=="1" IF "%PRINTER_TEXT%"=="BOZZ" SET "DATAMATRIX_PM_SOURCE=fromText==00000000000-0||"
IF NOT "%GRID_C_DATAMATRIX_PM%"=="" IF "%GENERA_DATAMATRIX_PM%"=="1" IF "%PRINTER_TEXT%"=="BOZZ" SET "DATAMATRIX_PM_SOURCE=fromText==00000000000-0||"

SET "FILENAME_SOURCE="
IF NOT "%GRID_C_FILENAME%"=="" SET "FILENAME_SOURCE=fromGrid==%GRID_C_FILENAME%||"
IF NOT "%GRID_C_FILENAME%"=="" IF "%RINOMINA_FILE%"=="1" IF "%PRINTER_TEXT%"=="BOZZ" SET "FILENAME_SOURCE=fromText==00000000000-0||"
IF NOT "%GRID_C_FILENAME%"=="" IF "%RINOMINA_FILE%"=="1" IF "%PRINTER_TEXT%"=="BOZZ" SET "FILENAME_SOURCE=fromText==00000000000-0||"

SET "TRAY_LETT="
IF NOT "%TRAY_N_LETT%"=="" SET "TRAY_LETT=||inputTray==%TRAY_N_LETT%"

SET "TRAY_PAGA="
IF NOT "%TRAY_N_PAGA%"=="" SET "TRAY_PAGA=||inputTray==%TRAY_N_PAGA%"

SET OP-0= & SET OP-1= & SET OP-2= & SET OP-3= & SET OP-4= & SET OP-5= & SET OP-6= & SET OP-7= & SET OP-8= & SET OP-9=
SET OP00= & SET OP01= & SET OP02= & SET OP03= & SET OP04= & SET OP05= & SET OP06= & SET OP07= & SET OP08= & SET OP09=
SET OP10= & SET OP11= & SET OP12= & SET OP13= & SET OP14= & SET OP15= & SET OP16= & SET OP17= & SET OP18= & SET OP19=
SET OP20= & SET OP21= & SET OP22= & SET OP23= & SET OP24= & SET OP25= & SET OP26= & SET OP27= & SET OP28= & SET OP29=
SET OP30= & SET OP31= & SET OP32= & SET OP33= & SET OP34= & SET OP35= & SET OP36= & SET OP37= & SET OP38= & SET OP39=
SET OP40= & SET OP41= & SET OP42= & SET OP43= & SET OP44= & SET OP45= & SET OP46= & SET OP47= & SET OP48= & SET OP49=
SET OP50= & SET OP51= & SET OP52=

IF "%PRINTER_TEXT%"=="CANO" SET WISH_T_LETT=%CANO_T_LETT%
IF "%PRINTER_TEXT%"=="CANO" SET WISH_L_LETT=%CANO_L_LETT%
IF "%PRINTER_TEXT%"=="CANO" SET WISH_Z_LETT=%CANO_Z_LETT%
IF "%PRINTER_TEXT%"=="CANO" SET WISH_T_PAGA=%CANO_T_PAGA%
IF "%PRINTER_TEXT%"=="CANO" SET WISH_L_PAGA=%CANO_L_PAGA%
IF "%PRINTER_TEXT%"=="CANO" SET WISH_Z_PAGA=%CANO_Z_PAGA%
IF "%PRINTER_TEXT%"=="CANO" SET WISH_T_ALLS=%CANO_T_ALLS%
IF "%PRINTER_TEXT%"=="CANO" SET WISH_L_ALLS=%CANO_L_ALLS%
IF "%PRINTER_TEXT%"=="CANO" SET WISH_Z_ALLS=%CANO_Z_ALLS%

IF "%PRINTER_TEXT%"=="RICO" SET WISH_T_LETT=%RICO_T_LETT%
IF "%PRINTER_TEXT%"=="RICO" SET WISH_L_LETT=%RICO_L_LETT%
IF "%PRINTER_TEXT%"=="RICO" SET WISH_Z_LETT=%RICO_Z_LETT%
IF "%PRINTER_TEXT%"=="RICO" SET WISH_T_PAGA=%RICO_T_PAGA%
IF "%PRINTER_TEXT%"=="RICO" SET WISH_L_PAGA=%RICO_L_PAGA%
IF "%PRINTER_TEXT%"=="RICO" SET WISH_Z_PAGA=%RICO_Z_PAGA%
IF "%PRINTER_TEXT%"=="RICO" SET WISH_T_ALLS=%RICO_T_ALLS%
IF "%PRINTER_TEXT%"=="RICO" SET WISH_L_ALLS=%RICO_L_ALLS%
IF "%PRINTER_TEXT%"=="RICO" SET WISH_Z_ALLS=%RICO_Z_ALLS%

IF "%PRINTER_TEXT%"=="FILE" SET WISH_T_LETT=%FILE_T_LETT%
IF "%PRINTER_TEXT%"=="FILE" SET WISH_L_LETT=%FILE_L_LETT%
IF "%PRINTER_TEXT%"=="FILE" SET WISH_Z_LETT=%FILE_Z_LETT%
IF "%PRINTER_TEXT%"=="FILE" SET WISH_T_PAGA=%FILE_T_PAGA%
IF "%PRINTER_TEXT%"=="FILE" SET WISH_L_PAGA=%FILE_L_PAGA%
IF "%PRINTER_TEXT%"=="FILE" SET WISH_Z_PAGA=%FILE_Z_PAGA%
IF "%PRINTER_TEXT%"=="FILE" SET WISH_T_ALLS=%FILE_T_ALLS%
IF "%PRINTER_TEXT%"=="FILE" SET WISH_L_ALLS=%FILE_L_ALLS%
IF "%PRINTER_TEXT%"=="FILE" SET WISH_Z_ALLS=%FILE_Z_ALLS%

IF "%PRINTER_TEXT%"=="OCTS" SET WISH_T_LETT=%OCTS_T_LETT%
IF "%PRINTER_TEXT%"=="OCTS" SET WISH_L_LETT=%OCTS_L_LETT%
IF "%PRINTER_TEXT%"=="OCTS" SET WISH_Z_LETT=%OCTS_Z_LETT%
IF "%PRINTER_TEXT%"=="OCTS" SET WISH_T_PAGA=%OCTS_T_PAGA%
IF "%PRINTER_TEXT%"=="OCTS" SET WISH_L_PAGA=%OCTS_L_PAGA%
IF "%PRINTER_TEXT%"=="OCTS" SET WISH_Z_PAGA=%OCTS_Z_PAGA%
IF "%PRINTER_TEXT%"=="OCTS" SET WISH_T_ALLS=%OCTS_T_ALLS%
IF "%PRINTER_TEXT%"=="OCTS" SET WISH_L_ALLS=%OCTS_L_ALLS%
IF "%PRINTER_TEXT%"=="OCTS" SET WISH_Z_ALLS=%OCTS_Z_ALLS%

rem "-1::(?s)(?i).*::0::0::0::0::formatImages==png||bwImages||bwFactor==0.925||resizeImages||resizeShortSide==2500" 
IF "%CHOICE_TEXT%"=="PRINT" IF "%ESCLUDI_PAGINE%"=="1" SET OP-9="-9::(?s)(?i).*?%SEARCH_SKIP%.*::%RECT_SKIP%::name==ESCLUDI_PAGINE||removePagesAt==-0::10::10::6"
IF "%CHOICE_TEXT%"=="PRINT" IF "%ELIMINA_PAGINE%"=="1" SET OP-8="-8::(?s)(?i).*?%SEARCH_VOID%.*::%RECT_VOID%::name==RIMUOVI_PAGINE||removePagesAt==-0::10::10::6"


IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%PREV_L_PAGA%_%PREV_T_PAGA%_%PREV_Z_PAGA%"=="__" IF NOT "%PREV_L_PAGA%_%PREV_T_PAGA%_%PREV_Z_PAGA%"=="0_0_100" SET OP-4="-4::(?s)(?i).*?%MATCH_SEARCH_PAGA%.*::%MATCH_RECT_PAGA%::name==MARGINI_PAGAMENTO_PRESTAMPA" "-4::(?s)(?i).*?%SEARCH_PAGA%.*::%RECT_PAGA%::name==MARGINI_PAGAMENTO_PRESTAMPA||marginTop==%PREV_T_PAGA%||marginLeft==%PREV_L_PAGA%||zoomPercent==%PREV_Z_PAGA%"
IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%PREV_L_LETT%_%PREV_T_LETT%_%PREV_Z_LETT%"=="__" IF NOT "%PREV_L_LETT%_%PREV_T_LETT%_%PREV_Z_LETT%"=="0_0_100" SET OP-5="-5::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==MARGINI_LETTERA_PRESTAMPA" "-5::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==MARGINI_LETTERA_PRESTAMPA||marginTop==%PREV_T_LETT%||marginLeft==%PREV_L_LETT%||zoomPercent==%PREV_Z_LETT%"
IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%PREV_L_ALLS%_%PREV_T_ALLS%_%PREV_Z_ALLS%"=="__" IF NOT "%PREV_L_ALLS%_%PREV_T_ALLS%_%PREV_Z_ALLS%"=="0_0_100" SET OP-6="-6::(?s)(?i).*?%SEARCH_ALLS%.*::%RECT_ALLS%::name==MARGINI_TUTTO_PRESTAMPA||marginTop==%PREV_T_ALLS%||marginLeft==%PREV_L_ALLS%||zoomPercent==%PREV_Z_ALLS%"

IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%PAGE_L_OMRS%_%PAGE_T_OMRS%_%PAGE_Z_OMRS%"=="0_0_100" SET OP-1="-1::(?s)(?i).*?%SEARCH_OMRP%.*::%RECT_OMRP%::name==MARGINI_OMR" "-1::(?s)(?i).*?%SEARCH_OMRS%.*::%RECT_OMRS%::name==MARGINI_OMR||marginTop==%PAGE_T_OMRS%||marginLeft==%PAGE_L_OMRS%||zoomPercent==%PAGE_Z_OMRS%"

IF "%CHOICE_TEXT%"=="PRINT" IF "%NASCONDI_ZONA%"=="1" SET OP00="00::(?s)(?i).*?%SEARCH_ZONE%.*::%RECT_ZONE%::name==NASCONDI_ZONE||drawRect||X==%HIDE_X_ZONE%||Y==%HIDE_Y_ZONE%||width==%HIDE_W_ZONE%||height==%HIDE_H_ZONE%"

IF "%SPOSTA_TESTO%"=="1" SET OP01="01::(?s)(?i).*?%SEARCH_TEXT%.*::%RECT_TEXT%::name==NASCONDI_TESTO||drawRect||X==%HIDE_X_TEXT%||Y==%HIDE_Y_TEXT%||width==%HIDE_W_TEXT%||height==%HIDE_H_TEXT%"
IF "%SPOSTA_TESTO%"=="1" SET OP02="02::(?s)(?i).*?%SEARCH_TEXT%.*::%RECT_TEXT%::name==COPIA_TESTO||fromMatch::%POSZ_X_TEXT%::%POSZ_Y_TEXT%::%FONT_S_TEXT%::0"

IF "%SPOSTA_INDIRIZZO%"=="1" SET OP03="03::(?s)(?i).*?%SEARCH_INDZ%.*::%RECT_INDZ%::name==NASCONDI_INDIRIZZO||drawRect||X==%HIDE_X_INDZ%||Y==%HIDE_Y_INDZ%||width==%HIDE_W_INDZ%||height==%HIDE_H_INDZ%"
IF "%SPOSTA_INDIRIZZO%"=="1" SET OP04="04::(?s)(?i).*?%SEARCH_INDZ%.*::%RECT_INDZ%::name==COPIA_INDIRIZZO||fromMatch||toTextRect||X==%POSZ_X_INDZ%||Y==%POSZ_Y_INDZ%||width==%POSZ_W_INDZ%||height==%POSZ_H_INDZ%||font==%FONT_S_INDZ%"
IF "%SPOSTA_INDIRIZZO%"=="1" SET OP05="05::(?s)(?i).*?%SEARCH_INDZ%.*::%RECT_INDZ_LUNG%::name==NASCONDI_INDIRIZZO_LUNGO||drawRect||X==%HIDE_X_INDZ%||Y==%HIDE_Y_INDZ%||width==%HIDE_W_INDZ%||height==%HIDE_H_INDZ%"
IF "%SPOSTA_INDIRIZZO%"=="1" SET OP06="06::(?s)(?i).*?%SEARCH_INDZ%.*::%RECT_INDZ_LUNG%::name==COPIA_INDIRIZZO_LUNGO||fromGroupMatch==5||toTextRect||X==%POSZ_X_INDZ%||Y==%POSZ_Y_INDZ%||width==%POSZ_W_INDZ%||height==%POSZ_H_INDZ%||font==%LONG_S_INDZ%"

IF "%CHOICE_TEXT%"=="PRINT" IF "%INSERISCI_IMMAGINE%"=="1" SET OP07="07::(?s)(?i).*?%SEARCH_IMAG%.*::%RECT_IMAG%::name==INSERISCI_IMMAGINE||fromImage==%SRCS_P_IMAG%||width==%POSZ_W_IMAG%||height==%POSZ_H_IMAG%::%POSZ_X_IMAG%::%POSZ_Y_IMAG%::0"

IF "%ATTO_IN_BARCODE%"=="1" IF NOT "%HIDE_X_CODE%_%HIDE_Y_CODE%_%HIDE_W_CODE%_%HIDE_H_CODE%"=="0_0_0_0" SET OP08="08::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==NASCONDI_ATTO" "08::(?s)(?i).*?%SEARCH_CODE%.*::%RECT_CODE%::nospaces||name==NASCONDI_ATTO||drawRect||X==%HIDE_X_CODE%||Y==%HIDE_Y_CODE%||width==%HIDE_W_CODE%||height==%HIDE_H_CODE%"
IF "%ATTO_IN_BARCODE%"=="1" SET OP09="09::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==ATTO_IN_BARCODE" "09::(?s)(?i).*?%SEARCH_CODE%.*::%RECT_CODE%::nospaces||name==ATTO_IN_BARCODE||%CODE_SOURCE%toBarcode==C128||barX==0.4||X==%POSZ_X_CODE%||Y==%POSZ_Y_CODE%||height==6||scalePercent==%ZOOM_S_CODE%||font==%FONT_S_CODE%"
IF "%TESTO_DA_GRIGLIA%"=="1" IF NOT "%HIDE_X_GRIDTEXT%_%HIDE_Y_GRIDTEXT%_%HIDE_W_GRIDTEXT%_%HIDE_H_GRIDTEXT%"=="0_0_0_0" SET OP40="40::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==NASCONDI_GRIDTEXT" "40::(?s)(?i).*?%SEARCH_GRIDTEXT%.*::%RECT_GRIDTEXT%::nospaces||name==NASCONDI_GRIDTEXT||drawRect||X==%HIDE_X_GRIDTEXT%||Y==%HIDE_Y_GRIDTEXT%||width==%HIDE_W_GRIDTEXT%||height==%HIDE_H_GRIDTEXT%"
IF "%TESTO_DA_GRIGLIA%"=="1" SET OP41="41::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==TESTO_DA_GRIGLIA" "41::(?s)(?i).*?%SEARCH_GRIDTEXT%.*::%RECT_GRIDTEXT%::nospaces||name==TESTO_DA_GRIGLIA||%GRIDTEXT_SOURCE%toText||X==%POSZ_X_GRIDTEXT%||Y==%POSZ_Y_GRIDTEXT%||height==10||font==%FONT_S_GRIDTEXT%"
IF "%BARCODE_TEXT%"=="1" IF NOT "%HIDE_X_BARCODETEXT%_%HIDE_Y_BARCODETEXT%_%HIDE_W_BARCODETEXT%_%HIDE_H_BARCODETEXT%"=="0_0_0_0" SET OP42="42::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==NASCONDI_BARCODETEXT" "42::(?s)(?i).*?%SEARCH_BARCODETEXT%.*::%RECT_BARCODETEXT%::nospaces||name==NASCONDI_BARCODETEXT||drawRect||X==%HIDE_X_BARCODETEXT%||Y==%HIDE_Y_BARCODETEXT%||width==%HIDE_W_BARCODETEXT%||height==%HIDE_H_BARCODETEXT%"
IF "%BARCODE_TEXT%"=="1" SET OP43="43::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_TEXT" "43::(?s)(?i).*?%SEARCH_BARCODETEXT%.*::%RECT_BARCODETEXT%::nospaces||name==BARCODE_TEXT||%BARCODETEXT_SOURCE%toText||X==%POSZ_X_BARCODETEXT%||Y==%POSZ_Y_BARCODETEXT%||height==6||font==%FONT_S_BARCODETEXT%"
IF "%COVER_INDIRIZZO%"=="1" IF NOT "%HIDE_X_GRIDADDRESS%_%HIDE_Y_GRIDADDRESS%_%HIDE_W_GRIDADDRESS%_%HIDE_H_GRIDADDRESS%"=="0_0_0_0" SET OP50="50::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==NASCONDI_GRIDADDRESS" "50::(?s)(?i).*?%SEARCH_GRIDADDRESS%.*::%RECT_GRIDADDRESS%::nospaces||name==NASCONDI_GRIDADDRESS||drawRect||X==%HIDE_X_GRIDADDRESS%||Y==%HIDE_Y_GRIDADDRESS%||width==%HIDE_W_GRIDADDRESS%||height==%HIDE_H_GRIDADDRESS%"
IF "%COVER_INDIRIZZO%"=="1" SET OP51="51::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==COVER_INDIRIZZO" "51::(?s)(?i).*?%SEARCH_GRIDADDRESS%.*::%RECT_GRIDADDRESS%::nospaces||name==COVER_INDIRIZZO||%GRIDADDRESS_SOURCE%toText||X==%POSZ_X_GRIDADDRESS%||Y==%POSZ_Y_GRIDADDRESS%||W==%POSZ_W_GRIDADDRESS%||H==%POSZ_H_GRIDADDRESS%||lineHeight==%LINE_H_GRIDADDRESS%||font==%FONT_S_GRIDADDRESS%"

IF "%GENERA_DATAMATRIX%"=="1" SET OP10="10::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==DATAMATRIX_CODICE" "10::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==DATAMATRIX_CODICE||%DATAMATRIX_SOURCE%[0-9A-Za-z]||toBarcode==DM||X==%POSZ_X_DATAMATRIX%||Y==%POSZ_Y_DATAMATRIX%||width==22||height==22||scalePercent==%ZOOM_S_DATAMATRIX%||font==%FONT_S_DATAMATRIX%::0::0::0"
IF "%GENERA_DATAMATRIX_PM%"=="1" SET OP44="44::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==DATAMATRIX_PM" "44::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==DATAMATRIX_PM||%DATAMATRIX_PM_SOURCE%[0-9A-Za-z]||toBarcode==DM||X==%POSZ_X_DATAMATRIX_PM%||Y==%POSZ_Y_DATAMATRIX_PM%||width==48||height==16||scalePercent==%ZOOM_S_DATAMATRIX_PM%||font==%FONT_S_DATAMATRIX_PM%::0::0::0"

IF "%GENERA_BARCODE%"=="AR" SET OP11="11::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_CODICE" "11::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE||%BARCODE_SOURCE%fromValueMatch==(?nB)^R[A-C][0-9]{9}IT$::0::0::0" "11::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE||%BARCODE_SOURCE%toBarcode==ITF_C128||barN==0.88||barX==0.324||baseline==5.5||height==13||scalePercent==%ZOOM_S_BARCODE%||barTextFrom==(?i)^([0-9]{11})([0-9]{1})$||barTextTo==$1-$2||fontPath==%FONT_P_BARCODE%::%POSZ_X_BARCODE%::%POSZ_Y_BARCODE%::%FONT_S_BARCODE%"
IF "%GENERA_BARCODE%"=="AR" SET OP12="12::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_TESTO1" "12::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO1||%BARCODE_SOURCE%fromValueMatch==(?nB)^R[A-C][0-9]{9}IT$::0::0::0" "12::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO1||fromText==Mod. 04204(Ex WS210)::%POSZ_X_BARCODE_T1%::%POSZ_Y_BARCODE_T1%::4::90"
IF "%GENERA_BARCODE%"=="AR" SET OP13="13::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_TESTO2" "13::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO2||%BARCODE_SOURCE%fromValueMatch==(?nB)^R[A-C][0-9]{9}IT$::0::0::0" "13::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO2||fromText==EP0804/EP0496 - St [3F]::%POSZ_X_BARCODE_T2%::%POSZ_Y_BARCODE_T2%::4::90"
IF "%GENERA_BARCODE%"=="AR" SET OP14="14::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_TESTO3" "14::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO3||%BARCODE_SOURCE%fromValueMatch==(?nB)^R[A-C][0-9]{9}IT$::0::0::0" "14::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO3||fromText==R||fontPath==%FONT_P_BARCODE%::%POSZ_X_BARCODE_T3%::%POSZ_Y_BARCODE_T3%::20"
IF "%GENERA_BARCODE%"=="AR" SET OP17="17::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_NO_TESTI" "17::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_NO_TESTI||%BARCODE_SOURCE%fromValueMatch==(?nB)^R[A-C][0-9]{9}IT$::0::0::0" "17::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_NO_TESTI||%BARCODE_SOURCE%fromValueMatch==(?n)^[0-9][0-9]{10}-?[0-9]$||drawRect||X==%POSZ_X_BARCODE_T3%||Y==%POSZ_Y_BARCODE_T1%||width==5||height==22::0::0::0"
IF "%GENERA_BARCODE%"=="AR" SET OP19="19::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_CODICE_ESTERO" "19::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE_ESTERO||%BARCODE_SOURCE%fromValueMatch==^R[ABCN][0-9]{9}IT$::0::0::0" "19::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE_ESTERO||%BARCODE_SOURCE%toBarcode==C39||barN==0.88||barX==0.324||scalePercent==80||barTextFrom==(?i)^([A-Z]{2})([0-9]{4})([0-9]{4})([0-9]{1})([A-Z]{2})||barTextTo==$1  $2 $3 $4  $5||baseline==5.5||height==13.5||fontPath==%FONT_P_BARCODE%::%POSZ_X_BARCODE_TE0%::%POSZ_Y_BARCODE_TE0%::%FONT_S_BARCODE%"
rem SET OP20="20::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_TESTO1_ESTERO" "20::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO1_ESTERO||%BARCODE_SOURCE%fromValueMatch==^R[ABCN][0-9]{9}IT$::0::0::0" "20::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO1_ESTERO||fromText==Mod. 04210A Ed. 08/13::%POSZ_X_BARCODE_TE1%::%POSZ_Y_BARCODE_TE1%::4::90"
rem SET OP24="24::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_TESTO2_ESTERO" "24::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO2_ESTERO||%BARCODE_SOURCE%fromValueMatch==^R[ABCN][0-9]{9}IT$::0::0::0" "24::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO2_ESTERO||fromText==EP 0810A - EP1893A - St. [3F]::%POSZ_X_BARCODE_TE2%::%POSZ_Y_BARCODE_TE2%::4::90"
IF "%GENERA_BARCODE%"=="AR" SET OP27="27::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_TESTO3_ESTERO" "27::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO3_ESTERO||%BARCODE_SOURCE%fromValueMatch==^R[ABCN][0-9]{9}IT$::0::0::0" "27::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO3_ESTERO||fromText==R||bold==1||fontPath==%FONT_P_BARCODE%::%POSZ_X_BARCODE_TE3%::%POSZ_Y_BARCODE_TE3%::24"

IF "%GENERA_BARCODE%"=="AG" SET OP11="11::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_CODICE" "11::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE||%BARCODE_SOURCE%fromValueMatch==(?nB)^R[A-C][0-9]{9}IT$::0::0::0" "11::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE||%BARCODE_SOURCE%toBarcode==ITF_C128||barN==0.88||barX==0.324||baseline==5.5||scalePercent==%ZOOM_S_BARCODE%||barTextFrom==(?i)^([0-9]{11})([0-9]{1})$||barTextTo==$1-$2::%POSZ_X_BARCODE%::%POSZ_Y_BARCODE%::%FONT_S_BARCODE%"
IF "%GENERA_BARCODE%"=="AG" SET OP12="12::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_TESTO1" "12::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE||%BARCODE_SOURCE%fromValueMatch==(?nB)^R[A-C][0-9]{9}IT$::0::0::0" "12::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO1||fromText==AG::%POSZ_X_BARCODE_T1%::%POSZ_Y_BARCODE_T1%::20"
IF "%GENERA_BARCODE%"=="AG" SET OP19="19::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_CODICE_ESTERO" "19::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE_ESTERO||%BARCODE_SOURCE%fromValueMatch==^R[ABCN][0-9]{9}IT$::0::0::0" "19::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE_ESTERO||%BARCODE_SOURCE%toBarcode==C39||barN==0.9||scalePercent==90||barTextFrom==(?i)^([A-Z]{2})([0-9]{4})([0-9]{4})([0-9]{1})([A-Z]{2})||barTextTo==$1  $2 $3 $4  $5||baseline==5.5||height==13.5||fontPath==%FONT_P_BARCODE%::%POSZ_X_BARCODE_TE0%::%POSZ_Y_BARCODE_TE0%::%FONT_S_BARCODE%"
IF "%GENERA_BARCODE%"=="AG" SET OP27="27::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_TESTO3_ESTERO" "27::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO3_ESTERO||%BARCODE_SOURCE%fromValueMatch==^R[ABCN][0-9]{9}IT$::0::0::0" "27::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO3_ESTERO||fromText==R||bold==1||fontPath==%FONT_P_BARCODE%::%POSZ_X_BARCODE_TE3%::%POSZ_Y_BARCODE_TE3%::24"

IF "%GENERA_BARCODE%"=="AM" SET OP11="11::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_CODICE" "11::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE||%BARCODE_SOURCE%fromValueMatch==(?nB)^R[A-C][0-9]{9}IT$::0::0::0" "11::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE||%BARCODE_SOURCE%toBarcode==ITF_C128||barN==0.88||barX==0.324||baseline==5.5||scalePercent==%ZOOM_S_BARCODE%||barTextFrom==(?i)^([0-9]{11})([0-9]{1})$||barTextTo==$1-$2::%POSZ_X_BARCODE%::%POSZ_Y_BARCODE%::%FONT_S_BARCODE%"
IF "%GENERA_BARCODE%"=="AM" SET OP12="12::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_TESTO1" "12::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE||%BARCODE_SOURCE%fromValueMatch==(?nB)^R[A-C][0-9]{9}IT$::0::0::0" "12::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO1||fromText==AGM||bold==5::%POSZ_X_BARCODE_T2%::%POSZ_Y_BARCODE_T2%::19::90"

IF "%GENERA_BARCODE%"=="RK" SET OP11="11::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_CODICE" "11::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE||%BARCODE_SOURCE%fromValueMatch==(?nB)^R[A-C][0-9]{9}IT$::0::0::0" "11::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE||%BARCODE_SOURCE%toBarcode==ITF_C128||barN==0.88||barX==0.324||baseline==5.5||scalePercent==%ZOOM_S_BARCODE%||barTextFrom==(?i)^([0-9]{11})([0-9]{1})$||barTextTo==$1-$2::%POSZ_X_BARCODE%::%POSZ_Y_BARCODE%::%FONT_S_BARCODE%"
IF "%GENERA_BARCODE%"=="RK" SET OP12="12::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_TESTO1" "12::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE||%BARCODE_SOURCE%fromValueMatch==(?nB)^R[A-C][0-9]{9}IT$::0::0::0" "12::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO1||fromText==RK||bold==1::%POSZ_X_BARCODE_T1%::%POSZ_Y_BARCODE_T1%::16"

IF "%GENERA_BARCODE%"=="RG" SET OP11="11::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_CODICE" "11::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE||%BARCODE_SOURCE%fromValueMatch==(?nB)^R[A-C][0-9]{9}IT$::0::0::0" "11::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE||%BARCODE_SOURCE%toBarcode==ITF_C128||barN==0.88||barX==0.324||baseline==5.5||scalePercent==%ZOOM_S_BARCODE%||barTextFrom==(?i)^([0-9]{11})([0-9]{1})$||barTextTo==$1-$2::%POSZ_X_BARCODE%::%POSZ_Y_BARCODE%::%FONT_S_BARCODE%"
IF "%GENERA_BARCODE%"=="RG" SET OP12="12::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_TESTO1" "12::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO1||%BARCODE_SOURCE%fromValueMatch==(?nB)^R[A-C][0-9]{9}IT$::0::0::0" "12::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO1||fromText==RAG||bold==1::%POSZ_X_BARCODE_T1%::%POSZ_Y_BARCODE_T1%::14::90"
IF "%GENERA_BARCODE%"=="RG" SET OP13="13::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_TESTO2" "13::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO2||%BARCODE_SOURCE%fromValueMatch==(?nB)^R[A-C][0-9]{9}IT$::0::0::0" "13::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO2||fromText==Mod. 01441 - Ed. 10-16 - EP2429/EP2430 - St. [3F]::%POSZ_X_BARCODE_T2%::%POSZ_Y_BARCODE_T2%::4::0"
IF "%GENERA_BARCODE%"=="RG" SET OP19="19::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_CODICE_ESTERO" "19::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE_ESTERO||%BARCODE_SOURCE%fromValueMatch==^R[ABCN][0-9]{9}IT$::0::0::0" "19::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_CODICE_ESTERO||%BARCODE_SOURCE%toBarcode==C39||barN==0.9||scalePercent==90||barTextFrom==(?i)^([A-Z]{2})([0-9]{4})([0-9]{4})([0-9]{1})([A-Z]{2})||barTextTo==$1  $2 $3 $4  $5||baseline==5.5||height==13.5||fontPath==%FONT_P_BARCODE%::%POSZ_X_BARCODE_TE0%::%POSZ_Y_BARCODE_TE0%::%FONT_S_BARCODE%"
IF "%GENERA_BARCODE%"=="RG" SET OP27="27::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==BARCODE_TESTO3_ESTERO" "27::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO3_ESTERO||%BARCODE_SOURCE%fromValueMatch==^R[ABCN][0-9]{9}IT$::0::0::0" "27::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==BARCODE_TESTO3_ESTERO||fromText==R||bold==1||fontPath==%FONT_P_BARCODE%::%POSZ_X_BARCODE_TE3%::%POSZ_Y_BARCODE_TE3%::24"

IF NOT "%TEXT_V_AUTH%"==""  SET OP16="16::(?s)(?i).*?%MATCH_SEARCH_AUTH%.*::%MATCH_RECT_AUTH%::name==AUTORIZZAZIONE" "16::(?s)(?i).*?%SEARCH_AUTH%.*::%RECT_AUTH%::nospaces||name==AUTORIZZAZIONE||fromText==%TEXT_V_AUTH%::%POSZ_X_AUTH%::%POSZ_Y_AUTH%::%FONT_S_AUTH%"
IF NOT "%TEXT_V_WORD%"==""  SET OP18="18::(?s)(?i).*?%MATCH_SEARCH_WORD%.*::%MATCH_RECT_WORD%::name==TESTO_AGGIUNTIVO" "18::(?s)(?i).*?%SEARCH_WORD%.*::%RECT_WORD%::nospaces||name==TESTO_AGGIUNTIVO||fromTextFormat==%TEXT_V_WORD%||toText::%POSZ_X_WORD%::%POSZ_Y_WORD%::%FONT_S_WORD%"

IF "%RINOMINA_FILE%"=="1" IF NOT "%PRINTER_TEXT%"=="BOZZ" IF "%CHOICE_TEXT%"=="PRINT" SET OP15="15::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==RINOMINA_FILE" "15::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==RINOMINA_FILE||%FILENAME_SOURCE%toFilenameAlphanumeric"

IF NOT "%PRINTER_TEXT%"=="BOZZ" IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%WISH_L_PAGA%_%WISH_T_PAGA%_%WISH_Z_PAGA%"=="__" IF NOT "%WISH_L_PAGA%_%WISH_T_PAGA%_%WISH_Z_PAGA%"=="0_0_100" SET OP21="21::(?s)(?i).*?%MATCH_SEARCH_PAGA%.*::%MATCH_RECT_PAGA%::name==MARGINI_PAGAMENTO_STAMPA" "21::(?s)(?i).*?%SEARCH_PAGA%.*::%RECT_PAGA%::name==MARGINI_PAGAMENTO_STAMPA||marginTop==%WISH_T_PAGA%||marginLeft==%WISH_L_PAGA%||zoomPercent==%WISH_Z_PAGA%"
IF NOT "%PRINTER_TEXT%"=="BOZZ" IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%WISH_L_LETT%_%WISH_T_LETT%_%WISH_Z_LETT%"=="__" IF NOT "%WISH_L_LETT%_%WISH_T_LETT%_%WISH_Z_LETT%"=="0_0_100" SET OP22="22::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==MARGINI_LETTERA_STAMPA" "22::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==MARGINI_LETTERA_STAMPA||marginTop==%WISH_T_LETT%||marginLeft==%WISH_L_LETT%||zoomPercent==%WISH_Z_LETT%"
IF NOT "%PRINTER_TEXT%"=="BOZZ" IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%WISH_L_ALLS%_%WISH_T_ALLS%_%WISH_Z_ALLS%"=="__" IF NOT "%WISH_L_ALLS%_%WISH_T_ALLS%_%WISH_Z_ALLS%"=="0_0_100" SET OP23="23::(?s)(?i).*?%SEARCH_ALLS%.*::%RECT_ALLS%::name==MARGINI_TUTTO_STAMPA||marginTop==%WISH_T_ALLS%||marginLeft==%WISH_L_ALLS%||zoomPercent==%WISH_Z_ALLS%"

rem IF "%CHOICE_TEXT%"=="PRINT" SET OP24="24::(?s)(?i)(?o).*?.*::%RECT_LETT%::name==OMR_AREA||drawRect||X==%POSZ_X_OMRS_R1%||Y==%POSZ_Y_OMRS_R1%||width==24||height==21"
IF NOT "%PRINTER_TEXT%"=="BOZZ" IF "%CHOICE_TEXT%"=="PRINT" SET OP25="25::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==OMR_CODICE" "25::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==OMR_CODICE||OMR||odd||X==%POSZ_X_OMRS%||Y==%POSZ_Y_OMRS%||step==3.633||width==20||height==0.6||paddingHorizontal==3||paddingVertical==10"
IF "%PRINTER_TEXT%"=="BOZZ" IF "%CHOICE_TEXT%"=="PRINT" SET OP25="25::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==OMR_CODICE" "25::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==OMR_CODICE||OMR||odd||X==%POSZ_X_OMRS%||Y==%POSZ_Y_OMRS%||step==3.633||width==20||height==0.6||color==-1||paddingHorizontal==3||paddingVertical==10"

rem duplex
IF "%CHOICE_TEXT%"=="PRINT" IF "%COVER_DUPLEX%"=="0" SET OP26="26::(?s)(?i)(?n).*?(?dict:isCover)DICT_isCover=([^\n]+)\n.*$::0::0::297::10::name==STAMPA_LETTERA_DUPLEX" "26::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==STAMPA_LETTERA_DUPLEX" "26::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==STAMPA_LETTERA_DUPLEX%TRAY_LETT%||%DUPLEX_SCALE%duplex||dpi==%DPI_N_LETT%"
IF "%CHOICE_TEXT%"=="PRINT" IF "%COVER_DUPLEX%"=="0" SET OP28="28::(?s)(?i).*?(?dict:isCover)DICT_isCover=([^\n]+)\n.*$::0::0::297::10::name==STAMPA_COVER_SIMPLEX||%SIMPLEX_SCALE%simplex%TRAY_LETT%||dpi==%DPI_N_LETT%"
SET /a PAGE_I_FXLS=%PAGE_I_FXLS%+1
IF "%CHOICE_TEXT%"=="PRINT" IF "%COVER_DUPLEX%"=="0" SET OP29="29::(?s)(?i).*?(?p%PAGE_I_FXLS%)(.*)::0::0::297::10::name==STAMPA_DOPO_COVER_DUPLEX||%DUPLEX_SCALE%duplex%TRAY_LETT%||dpi==%DPI_N_LETT%||fromGroupMatch==28||pageOffset==-1"
SET /a PAGE_I_FXLS=%PAGE_I_FXLS%-1

IF "%CHOICE_TEXT%"=="PRINT" SET OP52="52::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==INSERIMENTO_CUSTOMERCODE_LETT" "52::(?s)(?i).*?%SEARCH_LETT%.*$::%RECT_LETT%::name==INSERIMENTO_CUSTOMERCODE_LETT||toText==1||fromGridFormat==CUSTOMER_CODE:LETTERA_{%GRID_C_BARCODETIME%}||color==transparent::10::10::10"

IF "%CHOICE_TEXT%"=="PRINT" IF "%COVER_DUPLEX%"=="1" SET OP26="26::(?s)(?i)(?n).*?(?dict:isCover)DICT_isCover=([^\n]+)\n.*$::0::0::297::10::name==STAMPA_LETTERA_DUPLEX" "26::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==STAMPA_LETTERA_DUPLEX" "26::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==STAMPA_LETTERA_DUPLEX%TRAY_LETT%||%DUPLEX_SCALE%duplex||dpi==%DPI_N_LETT%"
IF "%CHOICE_TEXT%"=="PRINT" IF "%COVER_DUPLEX%"=="1" SET OP28="28::(?s)(?i).*?(?dict:isCover)DICT_isCover=([^\n]+)\n.*$::0::0::297::10::name==STAMPA_COVER_DUPLEX||%DUPLEX_SCALE%duplex%TRAY_LETT%||dpi==%DPI_N_LETT%"
SET /a PAGE_I_FXLS=%PAGE_I_FXLS%+1
SET /a PAGE_I_FXLS=%PAGE_I_FXLS%-1

IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%RECT_DUPLEX_A%"=="0::0::0::0" SET OP30="30::(?s)(?i).*?%SEARCH_DUPLEX_A%.*::%RECT_DUPLEX_A%::nospaces||name==STAMPA_DUPLEX_A||duplex||dpi==%DPI_N_LETT%"
IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%RECT_DUPLEX_A%"=="0::0::0::0" SET OP46="46::(?s)(?i).*?%SEARCH_DUPLEX_A%.*::%RECT_DUPLEX_A%::nospaces||name==INSERIMENTO_CUSTOMERCODE_DUPLEX_A" "46::(?s)(?i).*?%SEARCH_DUPLEX_A%.*$::%RECT_DUPLEX_A%::name==INSERIMENTO_CUSTOMERCODE_DUPLEX_A||toText==1||fromTextFormat==CUSTOMER_CODE:DUPLEX_A||color==transparent::10::10::10"
IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%RECT_DUPLEX_B%"=="0::0::0::0" SET OP31="31::(?s)(?i).*?%SEARCH_DUPLEX_B%.*::%RECT_DUPLEX_B%::nospaces||name==STAMPA_DUPLEX_B||duplex||dpi==%DPI_N_LETT%"
IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%RECT_DUPLEX_B%"=="0::0::0::0" SET OP47="47::(?s)(?i).*?%SEARCH_DUPLEX_B%.*::%RECT_DUPLEX_B%::nospaces||name==INSERIMENTO_CUSTOMERCODE_DUPLEX_B" "47::(?s)(?i).*?%SEARCH_DUPLEX_B%.*$::%RECT_DUPLEX_B%::name==INSERIMENTO_CUSTOMERCODE_DUPLEX_B||toText==1||fromTextFormat==CUSTOMER_CODE:DUPLEX_B||color==transparent::10::10::10"
IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%RECT_DUPLEX_C%"=="0::0::0::0" SET OP32="32::(?s)(?i).*?%SEARCH_DUPLEX_C%.*::%RECT_DUPLEX_C%::nospaces||name==STAMPA_DUPLEX_C||duplex||dpi==%DPI_N_LETT%"
IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%RECT_DUPLEX_C%"=="0::0::0::0" SET OP48="48::(?s)(?i).*?%SEARCH_DUPLEX_C%.*::%RECT_DUPLEX_C%::nospaces||name==INSERIMENTO_CUSTOMERCODE_DUPLEX_C" "48::(?s)(?i).*?%SEARCH_DUPLEX_C%.*$::%RECT_DUPLEX_C%::name==INSERIMENTO_CUSTOMERCODE_DUPLEX_C||toText==1||fromTextFormat==CUSTOMER_CODE:DUPLEX_C||color==transparent::10::10::10"
IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%RECT_DUPLEX_D%"=="0::0::0::0" SET OP33="33::(?s)(?i).*?%SEARCH_DUPLEX_D%.*::%RECT_DUPLEX_D%::nospaces||name==STAMPA_DUPLEX_D||duplex||dpi==%DPI_N_LETT%"
IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%RECT_DUPLEX_D%"=="0::0::0::0" SET OP49="49::(?s)(?i).*?%SEARCH_DUPLEX_D%.*::%RECT_DUPLEX_D%::nospaces||name==INSERIMENTO_CUSTOMERCODE_DUPLEX_D" "49::(?s)(?i).*?%SEARCH_DUPLEX_D%.*$::%RECT_DUPLEX_D%::name==INSERIMENTO_CUSTOMERCODE_DUPLEX_D||toText==1||fromTextFormat==CUSTOMER_CODE:DUPLEX_D||color==transparent::10::10::10"
IF "%CHOICE_TEXT%"=="PRINT" SET OP34="34::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==CONTEGGIO_PAGINE_EXPORT" "34::(?s)(?i).*?%SEARCH_LETT%.*::%RECT_LETT%::nospaces||name==CONTEGGIO_PAGINE_EXPORT||fromGridToCounters==%GRID_C_PAGES%::0::0::0"

rem simplex
IF "%CHOICE_TEXT%"=="PRINT" SET OP37="37::(?s)(?i).*?%MATCH_SEARCH_PAGA%.*::%MATCH_RECT_PAGA%::name==STAMPA_PAGAMENTO_SIMPLEX" "37::(?s)(?i).*?%SEARCH_PAGA%.*::%RECT_PAGA%::name==STAMPA_PAGAMENTO_SIMPLEX%TRAY_PAGA%||%SIMPLEX_SCALE%simplex||dpi==%DPI_N_PAGA%"
IF "%CHOICE_TEXT%"=="PRINT" SET OP45="45::(?s)(?i).*?%MATCH_SEARCH_PAGA%.*::%MATCH_RECT_PAGA%::name==INSERIMENTO_CUSTOMERCODE_PAGA" "45::(?s)(?i).*?%SEARCH_PAGA%.*$::%RECT_PAGA%::name==INSERIMENTO_CUSTOMERCODE_PAGA||toText==1||fromTextFormat==CUSTOMER_CODE:PAGAMENTO||color==transparent::10::10::10"

SET OPLU="0::(?s)(?i).*?%MATCH_SEARCH_LETT%.*::%MATCH_RECT_LETT%::name==SPLIT_LETTERA||previousOnError" "0::(?s)(?i).*?%SEARCH_LETT%.*$::%RECT_LETT%::nospaces||name==SPLIT_LETTERA||previousOnError||NONE::10::10::6"
SET OPPU="0::(?s)(?i).*?%MATCH_SEARCH_PAGA%.*::%MATCH_RECT_PAGA%::name==SPLIT_PAGAMENTO||previousOnError" "0::(?s)(?i).*?%SEARCH_PAGA%.*$::%RECT_PAGA%::name==SPLIT_PAGAMENTO||previousOnError||NONE::10::10::6"

SET OP0X="0::(?s)(?i).*?%SEARCH_FXLS%.*$::%RECT_FXLS%::name==INSERIMENTO_PAGINA_AGGIUNTIVA||insertPagesAt==%PAGE_I_FXLS%||fromGridFormat==;{%GRID_U_FXLS%};{%GRID_C_FXLS%::TRIM}||fromValueMatch==(?i)(?s).*?;(.+);.*?[^\s]+||NONE::210::10::6"

SET "LH="
IF NOT "%LINE_H_FXLS%"=="" SET "LH=||lineHeight==%LINE_H_FXLS%"
SET "LHAD="
IF NOT "%LINE_H_GRIDADDRESS%"=="" SET "LHAD=||lineHeight==%LINE_H_GRIDADDRESS%"

IF "%FORZA_DESTINATARIO_WHOLESALE%"=="0" SET OP2X="2::(?s)(?i).*?(?p%PAGE_I_FXLS%)(?dict:isCover)DICT_isCover=([^\n]+)\n.*$::0::0::297::10::name==INSERIMENTO_TESTO_AGGIUNTIVO||toText==1||fromGridFormat==%GRID_F_FXLS%||NONE%LH%::%POSZ_X_FXLS%::%POSZ_Y_FXLS%::%FONT_S_FXLS%"
IF "%FORZA_DESTINATARIO_WHOLESALE%"=="1" SET OP2X="2::(?s)(?i).*?(?p%PAGE_I_FXLS%)(?dict:isCover)DICT_isCover=([^\n]+)\n.*$::0::0::297::10::name==INSERIMENTO_TESTO_AGGIUNTIVO||toText==1||fromGridFormat==%GRID_G_FXLS%||NONE%LH%::115::240::10"
SET OP3X="3::(?s)(?i).*?(?p%PAGE_I_FXLS%)(?dict:isCover)DICT_isCover=([^\n]+)\n.*$::0::0::297::10::name==INSERIMENTO_IMMAGINE_RELATA||fromImage==%F_RELATA_PATH%||fromGrid==%RELA_C_FXLS%||fromValueMatch==(?i)(?s).*?RELATA.*?||width==%RELA_W_FXLS%||height==%RELA_H_FXLS%::%RELA_X_FXLS%::%RELA_Y_FXLS%::0"
SET /a RELA_X_FXLS=%RELA_X_FXLS%+3
SET /a RELA_Y_FXLS=%RELA_Y_FXLS%-%RELA_H_FXLS%+3
SET OP4X="4::(?s)(?i).*?(?p%PAGE_I_FXLS%)(?dict:isCover)DICT_isCover=([^\n]+)\n.*$::0::0::297::10::name==INSERIMENTO_TESTO_RELATA||toText==1||fromGridFormat==;{%RELA_C_FXLS%};%RELA_F_FXLS%||fromValueMatch==(?i)(?s).*?;[^;]*RELATA[^;]*;(.*)::%RELA_X_FXLS%::%RELA_Y_FXLS%::%RELA_S_FXLS%"

SET OP0P="0::(?s)(?i).*?%SEARCH_FPDF%.*$::%RECT_FPDF%::name==INSERIMENTO_PDF_AGGIUNTIVO||insertPagesAt==%PAGE_I_FPDF%||insertPagesWhat==%PAGE_P_FPDF%||NONE::10::10::6"
SET OP0B="0::(?s)(?i).*?%SEARCH_BLNK%.*$::%RECT_BLNK%::name==AGGIUNGI_PAGINE_VUOTE||insertPagesAt==%PAGE_I_BLNK%||insertPagesWhat==>%PAGE_P_BLNK%::210::10::6"
rem SET OP15="15::(?s)(?i).*?%SEARCH_PAGA%.*::%RECT_PAGA%::marginTop==-4||marginLeft==0||zoomPercent==98"
SET OPFV="-1::(?s)(?i).*::%RECT_PAGA%::name==RESET_ZOOM||zoomPercent==100"
SET OP0V="0::(?s)(?i).*::%RECT_PAGA%::name==PAGINE_IN_A4||maxSizeLongSide==297||maxSizeShortSide==210"
SET OP1V="0::(?s)(?i).*::%RECT_PAGA%::name==PAGINE_IN_VERTICALE||toVertical||zoomPercent==100"

SET OP1T="0::(?s)(?i).*?%SEARCH_CONV%.*$::%RECT_CONV%::name==INSERIMENTO_CUSTOMERCODE||toText==1||fromTextFormat==CUSTOMERCODE:{VALUE};||color==transparent::%POSZ_X_CONV%::%POSZ_Y_CONV%::%FONT_S_CONV%"

SET OP0E="0::(?p1)(?s)(?i).*?(?param:inputName)PARAM_inputName=(.+)\.pdf.*::0::0::0::0::name==NOMEFILE||toCSV"
SET OP1E="1::(?p1)(?s)(?i).*?%SEARCH_INDZ%.*::%RECT_INDZ%::name==INDIRIZZO||toCSV||trim"

SET OC0E="0::(?s)(?i)(?RENDER_IMAGE_BW:98).*RENDER_IMAGE_BW:98=0,0.*?::20::20::175::245::name==PROBABILI PAGINE BIANCHE::10::10::10::0"

SET "MAYBE_LOG="
rem IF "%GENERA_LOG%"=="1" SET MAYBE_LOG=2^>^>"%~1\ERRORS.txt" 1^>^>"%~1\LOG.txt"
rem IF "%GENERA_LOG%"=="0" SET MAYBE_LOG=2^>^>"%~1\ERRORS.txt"
rem SET MAYBE_LOG=%MAYBE_LOG%2^>^>  "%~1\ERRORS.txt" 
del /A /Q /F "%~1\LOG.txt" > NUL 2>&1
del /A /Q /F "%~1\ERRORS.txt" > NUL 2>&1
del /A /Q /F "%~1\REPORT.txt" > NUL 2>&1
rem echo del "%~1\log.txt"
rem SET PDFtoPDF_PATH=PDFtoPDF.jar
rem for %%i in (%PDFtoPDF_PATH%) do SET "PDFtoPDF_PATH=%%~dp$PATH:%iPDFtoPDF.jar"
rem echo %PDFtoPDF_PATH%
rem for %%i in (%PDFtoPDF_PATH%) do SET "PDFtoPDF_PATH=%%~fsi aaaa"
rem echo %PDFtoPDF_PATH%
rem pause
rem exit

rem SET OPS_DRAFT1=@OP-4@ @OP-5@ @OP-6@ @OP-7@ @OP-8@ @OP-9@ @OP-1@ @OP00@ @OP01@ @OP02@ @OP03@ @OP04@ @OP05@ @OP06@ @OP07@ @OP08@ @OP09@ @OP10@ @OP11@ @OP12@ @OP13@ @OP14@ @OP15@ @OP16@ @OP17@ @OP18@ @OP19@ @OP20@ @OP24@ @OP26@ @OP27@ @OP28@ @OP29@ @OP30@ @OP31@ @OP32@ @OP33@ @OP37@
SET OPS_DRAFT1=OPS_DRAFT1_%DATE%_%TIME%_%RANDOM%.cmds
SET OPS_DRAFT1=%OPS_DRAFT1:/=-%
SET OPS_DRAFT1=%OPS_DRAFT1::=-%
SET OPS_DRAFT1=%OPS_DRAFT1:,=-%
SET OPS_DRAFT1="%TEMP%\%OPS_DRAFT1%"
rem SET OPS_DRAFT1="%~1\OPS_DRAFT1.cmds"
del /A /Q /F %OPS_DRAFT1% > NUL 2>&1
echo %OP-4%>>%OPS_DRAFT1% & echo %OP-5%>>%OPS_DRAFT1% & echo %OP-6%>>%OPS_DRAFT1% & echo %OP-7%>>%OPS_DRAFT1% & echo %OP-8%>>%OPS_DRAFT1% & echo %OP-9%>>%OPS_DRAFT1% & echo %OP-1%>>%OPS_DRAFT1% & echo %OP00%>>%OPS_DRAFT1% & echo %OP01%>>%OPS_DRAFT1% & echo %OP02%>>%OPS_DRAFT1%
echo %OP03%>>%OPS_DRAFT1% & echo %OP04%>>%OPS_DRAFT1% & echo %OP05%>>%OPS_DRAFT1% & echo %OP06%>>%OPS_DRAFT1% & echo %OP07%>>%OPS_DRAFT1% & echo %OP08%>>%OPS_DRAFT1% & echo %OP09%>>%OPS_DRAFT1% & echo %OP10%>>%OPS_DRAFT1% & echo %OP11%>>%OPS_DRAFT1% & echo %OP12%>>%OPS_DRAFT1%
echo %OP13%>>%OPS_DRAFT1% & echo %OP14%>>%OPS_DRAFT1% & echo %OP15%>>%OPS_DRAFT1% & echo %OP16%>>%OPS_DRAFT1% & echo %OP17%>>%OPS_DRAFT1% & echo %OP18%>>%OPS_DRAFT1% & echo %OP19%>>%OPS_DRAFT1% & echo %OP20%>>%OPS_DRAFT1% & echo %OP24%>>%OPS_DRAFT1% & echo %OP26%>>%OPS_DRAFT1%
echo %OP27%>>%OPS_DRAFT1% & echo %OP28%>>%OPS_DRAFT1% & echo %OP29%>>%OPS_DRAFT1% & echo %OP30%>>%OPS_DRAFT1% & echo %OP31%>>%OPS_DRAFT1% & echo %OP32%>>%OPS_DRAFT1% & echo %OP33%>>%OPS_DRAFT1% & echo %OP37%>>%OPS_DRAFT1% & echo %OP40%>>%OPS_DRAFT1% & echo %OP41%>>%OPS_DRAFT1%
echo %OP42%>>%OPS_DRAFT1% & echo %OP43%>>%OPS_DRAFT1% & echo %OP44%>>%OPS_DRAFT1% & echo %OP45%>>%OPS_DRAFT1% & echo %OP46%>>%OPS_DRAFT1% & echo %OP47%>>%OPS_DRAFT1% & echo %OP48%>>%OPS_DRAFT1% & echo %OP49%>>%OPS_DRAFT1% & echo %OP50%>>%OPS_DRAFT1% & echo %OP51%>>%OPS_DRAFT1%
echo %OP52%>>%OPS_DRAFT1%

rem SET OPS_PRINT1=@OP-4@ @OP-5@ @OP-6@ @OP-7@ @OP-8@ @OP-9@ @OP-1@ @OP00@ @OP01@ @OP02@ @OP03@ @OP04@ @OP05@ @OP06@ @OP07@ @OP08@ @OP09@ @OP10@ @OP11@ @OP12@ @OP13@ @OP14@ @OP15@ @OP16@ @OP17@ @OP18@ @OP19@ @OP20@ @OP24@ @OP26@ @OP27@ @OP28@ @OP29@ @OP30@ @OP31@ @OP32@ @OP33@ @OP37@
SET OPS_PRINT1=OPS_PRINT1_%DATE%_%TIME%_%RANDOM%.cmds
SET OPS_PRINT1=%OPS_PRINT1:/=-%
SET OPS_PRINT1=%OPS_PRINT1::=-%
SET OPS_PRINT1=%OPS_PRINT1:,=-%
SET OPS_PRINT1="%TEMP%\%OPS_PRINT1%"
rem SET OPS_PRINT1="%~1\OPS_PRINT1.cmds"
del /A /Q /F %OPS_PRINT1% > NUL 2>&1
echo %OP-4%>>%OPS_PRINT1% & echo %OP-5%>>%OPS_PRINT1% & echo %OP-6%>>%OPS_PRINT1% & echo %OP-7%>>%OPS_PRINT1% & echo %OP-8%>>%OPS_PRINT1% & echo %OP-9%>>%OPS_PRINT1% & echo %OP-1%>>%OPS_PRINT1% & echo %OP00%>>%OPS_PRINT1% & echo %OP01%>>%OPS_PRINT1% & echo %OP02%>>%OPS_PRINT1%
echo %OP03%>>%OPS_PRINT1% & echo %OP04%>>%OPS_PRINT1% & echo %OP05%>>%OPS_PRINT1% & echo %OP06%>>%OPS_PRINT1% & echo %OP07%>>%OPS_PRINT1% & echo %OP08%>>%OPS_PRINT1% & echo %OP09%>>%OPS_PRINT1% & echo %OP10%>>%OPS_PRINT1% & echo %OP11%>>%OPS_PRINT1% & echo %OP12%>>%OPS_PRINT1%
echo %OP13%>>%OPS_PRINT1% & echo %OP14%>>%OPS_PRINT1% & echo %OP15%>>%OPS_PRINT1% & echo %OP16%>>%OPS_PRINT1% & echo %OP17%>>%OPS_PRINT1% & echo %OP18%>>%OPS_PRINT1% & echo %OP19%>>%OPS_PRINT1% & echo %OP20%>>%OPS_PRINT1% & echo %OP24%>>%OPS_PRINT1% & echo %OP26%>>%OPS_PRINT1%
echo %OP27%>>%OPS_PRINT1% & echo %OP28%>>%OPS_PRINT1% & echo %OP29%>>%OPS_PRINT1% & echo %OP30%>>%OPS_PRINT1% & echo %OP31%>>%OPS_PRINT1% & echo %OP32%>>%OPS_PRINT1% & echo %OP33%>>%OPS_PRINT1% & echo %OP37%>>%OPS_PRINT1% & echo %OP40%>>%OPS_PRINT1% & echo %OP41%>>%OPS_PRINT1%
echo %OP34%>>%OPS_PRINT1% & echo %OP42%>>%OPS_PRINT1% & echo %OP43%>>%OPS_PRINT1% & echo %OP44%>>%OPS_PRINT1% & echo %OP45%>>%OPS_PRINT1% & echo %OP46%>>%OPS_PRINT1% & echo %OP47%>>%OPS_PRINT1% & echo %OP48%>>%OPS_PRINT1% & echo %OP49%>>%OPS_PRINT1%
echo %OP50%>>%OPS_PRINT1% & echo %OP51%>>%OPS_PRINT1% & echo %OP52%>>%OPS_PRINT1%

rem SET OPS_PRINT2=@OP21@ @OP22@ @OP23@ @OP25@ @OP26@ @OP28@ @OP29@ @OP30@ @OP31@ @OP32@ @OP33@ @OP37@
SET OPS_PRINT2=OPS_PRINT2_%DATE%_%TIME%_%RANDOM%.cmds
SET OPS_PRINT2=%OPS_PRINT2:/=-%
SET OPS_PRINT2=%OPS_PRINT2::=-%
SET OPS_PRINT2=%OPS_PRINT2:,=-%
SET OPS_PRINT2="%TEMP%\%OPS_PRINT2%"
rem SET OPS_PRINT2="%~1\OPS_PRINT2.cmds"
del /A /Q /F %OPS_PRINT2% > NUL 2>&1
echo %OP21%>>%OPS_PRINT2% & echo %OP22%>>%OPS_PRINT2% & echo %OP23%>>%OPS_PRINT2% & echo %OP25%>>%OPS_PRINT2% & echo %OP26%>>%OPS_PRINT2% & echo %OP28%>>%OPS_PRINT2% & echo %OP29%>>%OPS_PRINT2% & echo %OP30%>>%OPS_PRINT2% & echo %OP31%>>%OPS_PRINT2% & echo %OP32%>>%OPS_PRINT2%
echo %OP33%>>%OPS_PRINT2% & echo %OP37%>>%OPS_PRINT2%

SET "PRINTERID="
SET "FILESERVICE="
rem rem IF NOT "%PRINTER_TEXT%"=="BOZZ" IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%PRINTER_TEXT%"=="FILE" IF NOT "%PRINTER_TEXT%"=="OCTS" SET "FILESERVICE=%TEMP%\printServiceGet_%date:~6,4%_%date:~3,2%_%date:~0,2%_%time:~0,2%_%time:~3,2%_%time:~6,2%_%time:~9,2%.dat"
rem IF NOT "%PRINTER_TEXT%"=="BOZZ" IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%PRINTER_TEXT%"=="FILE" IF NOT "%PRINTER_TEXT%"=="OCTS" for /f "skip=1" %%x in ('wmic os get localdatetime') do set "FILESERVICE=printServiceGet_%%x.dat"
rem IF NOT "%FILESERVICE%"=="" java -noverify -jar "%PDFtoPDF_PATH%" "" "printServiceGet::printServiceToFile==%FILESERVICE%"
rem IF NOT "%FILESERVICE%"=="" for /f "delims=" %%i in (%FILESERVICE%) do set PRINTERID=%%i
rem IF NOT "%FILESERVICE%"=="" del /F /Q "%FILESERVICE%"
rem echo %PRINTERID%
rem IF NOT "%PRINTER_TEXT%"=="PREP" IF NOT "%PRINTER_TEXT%"=="BOZZ" IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%PRINTER_TEXT%"=="FILE" IF NOT "%PRINTER_TEXT%"=="OCTS" IF "%PRINTERID%"=="Working" goto END
rem IF NOT "%PRINTER_TEXT%"=="PREP" IF NOT "%PRINTER_TEXT%"=="BOZZ" IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%PRINTER_TEXT%"=="FILE" IF NOT "%PRINTER_TEXT%"=="OCTS" IF "%PRINTERID%"=="" goto END
IF NOT "%PRINTER_TEXT%"=="PREP" IF NOT "%PRINTER_TEXT%"=="BOZZ" IF "%CHOICE_TEXT%"=="PRINT" IF NOT "%PRINTER_TEXT%"=="FILE" IF NOT "%PRINTER_TEXT%"=="OCTS" SET PARAMS_PRINT=%PARAMS_PRINT%::printServiceSet==%PRINTERID%
IF NOT "%PRINTER_TEXT%"=="PREP" IF NOT "%PRINTER_TEXT%"=="BOZZ" IF "%CHOICE_TEXT%"=="PRINT" IF "%PRINTER_TEXT%"=="OCTS" SET PARAMS_PRINT=%PARAMS_PRINT%::printServiceSet==PDF::printServicePath==%~1\OCT

IF "%PROCEDURA_ACCURATA%"=="1" SET "PARAMS=%PARAMS%::readerMode==page"

SET "PARAMS_MERGE=athreads==3"
IF "%PROCEDURA_ACCURATA%"=="1" SET "PARAMS_MERGE=%PARAMS_MERGE%::readerMode==page"

SET "PARAMS_LET=%PARAMS%::athreads==3"
IF "%RIMUOVI_MODULI_LETTERA%"=="1" SET "PARAMS_LET=%PARAMS_LET%::delForms"

SET "PARAMS_PAG=%PARAMS%::athreads==3"
IF "%RIMUOVI_INUTILIZZATI%"=="1" SET "PARAMS_PAG=%PARAMS_PAG%::delUnusedImages"
IF "%RIMUOVI_MODULI%"=="1" SET "PARAMS_PAG=%PARAMS_PAG%::delForms"

SET "PARAMS_VER=%PARAMS%"
IF "%RIMUOVI_INUTILIZZATI%"=="1" SET "PARAMS_VER=%PARAMS_VER%::delUnusedImages"
IF "%RIMUOVI_MODULI%"=="1" SET "PARAMS_VER=%PARAMS_VER%::delForms"
IF "%PROFILO_UNIONE%"=="CREARCI" SET OPFV="-1::(?s)(?i).*::%RECT_PAGA%::name==NORESET_ZOOM"

SET "SKIP_ERRORS="
IF "%CHOICE_TEXT%"=="UNION" (
	IF EXIST "%~1\ATTI" SET "ERROR=ESISTE GIA' LA CARTELLA %~1\ATTI" & GOTO ERROR
	IF EXIST "%~1\LETTERE\output" rmdir /S /Q "%~1\LETTERE\output" > NUL 2>&1
	IF EXIST "%~1\LETTERE\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\LETTERE\output" & GOTO ERROR
	IF EXIST "%~1\PAGAMENTI\output" rmdir /S /Q "%~1\PAGAMENTI\output" > NUL 2>&1
	IF EXIST "%~1\PAGAMENTI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\PAGAMENTI\output" & GOTO ERROR
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo --------------- Elaborazione LETTERE --------------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	rem del /A /S /Q /F "%~1\LETTERE\output"
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\LETTERE" "%PARAMS_LET%" "(?s)(?i).*?%SEARCH_PAGE%.*::%RECT_PAGE%" %OPLU% %MAYBE_LOG%
	mkdir "%~1\PAGAMENTI\output" > NUL 2>&1
	IF NOT EXIST "%~1\PAGAMENTI\output" SET "ERROR=IMPOSSIBILE CREARE LA CARTELLA %~1\PAGAMENTI\output" & GOTO ERROR
	move /Y "%~1\LETTERE\output\split" "%~1\PAGAMENTI\output\split" > NUL 2>&1
	IF NOT EXIST "%~1\PAGAMENTI\output\split" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\LETTERE\output\split" & GOTO ERROR
	rmdir /S /Q "%~1\LETTERE\output" > NUL 2>&1
	IF EXIST "%~1\LETTERE\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\LETTERE\output" & GOTO ERROR
	rem IF NOT "%GENERA_LOG%"=="1" IF NOT "%GENERA_LOG%"=="2" timeout 9
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo --------------- Elaborazione PAGAMENTI ------------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	rem del /A /S /Q /F "%~1\PAGAMENTI\output"
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\PAGAMENTI" "%PARAMS_PAG%" "(?s)(?i).*?%SEARCH_PAGE%.*::%RECT_PAGE%" %OPPU% %MAYBE_LOG%
	rem IF NOT "%GENERA_LOG%"=="1" IF NOT "%GENERA_LOG%"=="2" timeout 9
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo --------------- Elaborazione UNIONE ---------------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\PAGAMENTI\output\split" "merge" "%PARAMS_MERGE%" %MAYBE_LOG%
	IF EXIST "%~1\REPORT.txt" cmd /C notepad.exe "%~1\REPORT.txt"
	move /Y "%~1\PAGAMENTI\output\split\output\merge" "%~1\ATTI" > NUL 2>&1
	IF NOT EXIST "%~1\ATTI" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\PAGAMENTI\output\split\output\merge" & GOTO ERROR
	rmdir /S /Q "%~1\PAGAMENTI\output" > NUL 2>&1
	IF EXIST "%~1\PAGAMENTI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\PAGAMENTI\output" & GOTO ERROR
) ELSE IF "%CHOICE_TEXT%"=="ONION" (
	SET "SKIP_ERRORS=1"
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo ---------- Elaborazione MERGE/UNIONE OCT ----------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1" "%PARAMS%" %MAYBE_LOG%
) ELSE IF "%CHOICE_TEXT%"=="SPLIT" (
	IF EXIST "%~1\DIVISI" SET "ERROR=ESISTE GIA' LA CARTELLA %~1\DIVISI" & GOTO ERROR
	IF EXIST "%~1\ORIGINALI\output" rmdir /S /Q "%~1\ORIGINALI\output" > NUL 2>&1
	IF EXIST "%~1\ORIGINALI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ORIGINALI\output" & GOTO ERROR
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo ---------- DIVISIONE IN INTERVALLO PAGINE ---------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ORIGINALI" "%PARAMS%" "" %MAYBE_LOG%
	IF EXIST "%~1\REPORT.txt" cmd /C notepad.exe "%~1\REPORT.txt"
	move /Y "%~1\ORIGINALI\output" "%~1\DIVISI" > NUL 2>&1
	IF NOT EXIST "%~1\DIVISI" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\ORIGINALI\output" & GOTO ERROR
) ELSE IF "%CHOICE_TEXT%"=="TRANS" (
	IF EXIST "%~1\TRASFORMATI" SET "ERROR=ESISTE GIA' LA CARTELLA %~1\TRASFORMATI" & GOTO ERROR
	IF EXIST "%~1\ORIGINALI\output" rmdir /S /Q "%~1\ORIGINALI\output" > NUL 2>&1
	IF EXIST "%~1\ORIGINALI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ORIGINALI\output" & GOTO ERROR
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo ------------- PAGINE IN IMMAGINI ------------------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ORIGINALI" "%PARAMS%" "(?s)(?i).*?%MATCH_SEARCH_CONV%.*::%MATCH_RECT_CONV%" %OP1T% %MAYBE_LOG%
	IF EXIST "%~1\REPORT.txt" cmd /C notepad.exe "%~1\REPORT.txt"
	move /Y "%~1\ORIGINALI\output" "%~1\TRASFORMATI" > NUL 2>&1
	IF NOT EXIST "%~1\TRASFORMATI" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\ORIGINALI\output" & GOTO ERROR
) ELSE IF "%CHOICE_TEXT%"=="COUNT" (
	IF EXIST "%~1\ATTI\output" rmdir /S /Q "%~1\ATTI\output" > NUL 2>&1
	IF EXIST "%~1\ATTI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ATTI\output" & GOTO ERROR
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo -------------------- Conteggio  -------------------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ATTI" "%PARAMS%" "(?s)(?i).*?%SEARCH_PAGE%.*::%RECT_PAGE%" %OC0E% %MAYBE_LOG%
	IF EXIST "%~1\ATTI\output" rmdir /S /Q "%~1\ATTI\output" > NUL 2>&1
	IF EXIST "%~1\ATTI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ATTI\output" & GOTO ERROR
	IF EXIST "%~1\REPORT.txt" cmd /C notepad.exe "%~1\REPORT.txt"
) ELSE IF "%CHOICE_TEXT%"=="EXPRT" (
	IF EXIST "%~1\EXPORT.CSV" SET "ERROR=ESISTE GIA' IL FILE %~1\EXPORT.CSV" & GOTO ERROR
	IF EXIST "%~1\ATTI\output" rmdir /S /Q "%~1\ATTI\output" > NUL 2>&1
	IF EXIST "%~1\ATTI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ATTI\output" & GOTO ERROR
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo ------------- Esportazione INDIRIZZI --------------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ATTI" "%PARAMS%" "(?s)(?i).*?%SEARCH_PAGE%.*::%RECT_PAGE%" %OP0E% %OP1E% %MAYBE_LOG%
	move /Y "%~1\ATTI\output\export.csv" "%~1\EXPORT.CSV" > NUL 2>&1
	IF EXIST "%~1\REPORT.txt" cmd /C notepad.exe "%~1\REPORT.txt"
) ELSE IF "%CHOICE_TEXT%"=="F24PG" (
	IF EXIST "%~1\F24" SET "ERROR=ESISTE GIA' LA CARTELLA %~1\F24" & GOTO ERROR
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo ------------- Generazione F24 ---------------------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\F24" "%PARAMS%" "%F_PROFILE_PATH%" %MAYBE_LOG%
	IF EXIST "%~1\REPORT.txt" cmd /C notepad.exe "%~1\REPORT.txt"
) ELSE IF "%CHOICE_TEXT%"=="VERTI" (
	IF EXIST "%~1\VERTICALI" SET "ERROR=ESISTE GIA' LA CARTELLA %~1\VERTICALI" & GOTO ERROR
	IF EXIST "%~1\ORIZZONTALI\output" rmdir /S /Q "%~1\ORIZZONTALI\output" > NUL 2>&1
	IF EXIST "%~1\ORIZZONTALI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ORIZZONTALI\output" & GOTO ERROR
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo ------------- PAGINE IN A4 ------------------------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ORIZZONTALI" "%PARAMS_VER%" "(?s)(?i).*?%SEARCH_PAGE%.*::%RECT_PAGE%" %OPFV% %OP0V% %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo ------------- PAGINE IN VERTICALE ------------------ %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ORIZZONTALI\output" "%PARAMS%" "(?s)(?i).*?%SEARCH_PAGE%.*::%RECT_PAGE%" %OP1V% %MAYBE_LOG%
	IF EXIST "%~1\REPORT.txt" cmd /C notepad.exe "%~1\REPORT.txt"
	move /Y "%~1\ORIZZONTALI\output\output" "%~1\VERTICALI" > NUL 2>&1
	IF NOT EXIST "%~1\VERTICALI" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\ORIZZONTALI\output\output" & GOTO ERROR
	rmdir /S /Q "%~1\ORIZZONTALI\output" > NUL 2>&1
	IF EXIST "%~1\ORIZZONTALI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ORIZZONTALI\output" & GOTO ERROR
) ELSE IF "%CHOICE_TEXT%"=="BYBLK" (
	IF EXIST "%~1\ATTI_ORIGINALI" SET "ERROR=ESISTE GIA' LA CARTELLA %~1\ATTI_ORIGINALI" & GOTO ERROR
	IF EXIST "%~1\ATTI\output" rmdir /S /Q "%~1\ATTI\output" > NUL 2>&1
	IF EXIST "%~1\ATTI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ATTI\output" & GOTO ERROR
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo --------------- INSERIMENTO PAGINE VUOTE --------------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ATTI" "%PARAMS%::threads==8" "(?s)(?i).*?%SEARCH_PAGE%.*::%RECT_PAGE%" %OP0B% %MAYBE_LOG%
	IF EXIST "%~1\REPORT.txt" cmd /C notepad.exe "%~1\REPORT.txt"
	move /Y "%~1\ATTI" "%~1\ATTI_ORIGINALI" > NUL 2>&1
	IF NOT EXIST "%~1\ATTI_ORIGINALI" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\ATTI" & GOTO ERROR
	move /Y "%~1\ATTI_ORIGINALI\output" "%~1\ATTI" > NUL 2>&1
	IF NOT EXIST "%~1\ATTI" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\ATTI_ORIGINALI\output" & GOTO ERROR
	rmdir /S /Q "%~1\ATTI_ORIGINALI\output" > NUL 2>&1
	IF EXIST "%~1\ATTI_ORIGINALI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ATTI_ORIGINALI\output" & GOTO ERROR
) ELSE IF "%CHOICE_TEXT%"=="BWRES" (
	IF EXIST "%~1\ATTI_ORIGINALI" SET "ERROR=ESISTE GIA' LA CARTELLA %~1\ATTI_ORIGINALI" & GOTO ERROR
	IF EXIST "%~1\ATTI\output" rmdir /S /Q "%~1\ATTI\output" > NUL 2>&1
	IF EXIST "%~1\ATTI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ATTI\output" & GOTO ERROR
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo ---------- Riduzione Dimensioni Immagini ----------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ATTI" "%PARAMS%::threads==8" "(?s)(?i).*::0::0::0::0::rect::absolute::compress::loopDirs::noErrors" "-1::(?s)(?i).*::0::0::0::0::formatImages==png||bwImages||bwFactor==0.925||resizeImages||resizeShortSide==2000" 

	IF EXIST "%~1\REPORT.txt" cmd /C notepad.exe "%~1\REPORT.txt"
	move /Y "%~1\ATTI" "%~1\ATTI_ORIGINALI" > NUL 2>&1
	IF NOT EXIST "%~1\ATTI_ORIGINALI" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\ATTI" & GOTO ERROR
	move /Y "%~1\ATTI_ORIGINALI\output" "%~1\ATTI" > NUL 2>&1
	IF NOT EXIST "%~1\ATTI" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\ATTI_ORIGINALI\output" & GOTO ERROR
	rmdir /S /Q "%~1\ATTI_ORIGINALI\output" > NUL 2>&1
	IF EXIST "%~1\ATTI_ORIGINALI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ATTI_ORIGINALI\output" & GOTO ERROR
) ELSE IF "%CHOICE_TEXT%"=="BYPDF" (
	IF EXIST "%~1\ATTI_ORIGINALI" SET "ERROR=ESISTE GIA' LA CARTELLA %~1\ATTI_ORIGINALI" & GOTO ERROR
	IF EXIST "%~1\ATTI\output" rmdir /S /Q "%~1\ATTI\output" > NUL 2>&1
	IF EXIST "%~1\ATTI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ATTI\output" & GOTO ERROR
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo --------------- INSERIMENTO FILE PDF --------------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ATTI" "%PARAMS%::threads==8" "(?s)(?i).*?%SEARCH_PAGE%.*::%RECT_PAGE%" %OP0P% %MAYBE_LOG%
	IF EXIST "%~1\REPORT.txt" cmd /C notepad.exe "%~1\REPORT.txt"
	move /Y "%~1\ATTI" "%~1\ATTI_ORIGINALI" > NUL 2>&1
	IF NOT EXIST "%~1\ATTI_ORIGINALI" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\ATTI" & GOTO ERROR
	move /Y "%~1\ATTI_ORIGINALI\output" "%~1\ATTI" > NUL 2>&1
	IF NOT EXIST "%~1\ATTI" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\ATTI_ORIGINALI\output" & GOTO ERROR
	rmdir /S /Q "%~1\ATTI_ORIGINALI\output" > NUL 2>&1
	IF EXIST "%~1\ATTI_ORIGINALI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ATTI_ORIGINALI\output" & GOTO ERROR
) ELSE IF "%CHOICE_TEXT%"=="BYXLS" (
	IF EXIST "%~1\ATTI_ORIGINALI" SET "ERROR=ESISTE GIA' LA CARTELLA %~1\ATTI_ORIGINALI" & GOTO ERROR
	IF EXIST "%~1\ATTI\output" rmdir /S /Q "%~1\ATTI\output" > NUL 2>&1
	IF EXIST "%~1\ATTI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ATTI\output" & GOTO ERROR
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo ------------- INSERIMENTO PAGINA VUOTA ------------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ATTI" "%PARAMS%" "(?s)(?i).*?%SEARCH_PAGE%.*::%RECT_PAGE%" %OP0X% %MAYBE_LOG%
	rem IF NOT "%GENERA_LOG%"=="1" IF NOT "%GENERA_LOG%"=="2" timeout 9
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo ----------- INSERIMENTO TESTO AGGIUNTIVO ----------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ATTI\output" "%PARAMS%" "(?s)(?i).*?%SEARCH_PAGE%.*::%RECT_PAGE%" %OP2X% %OP3X% %OP4X% %MAYBE_LOG%
	IF EXIST "%~1\REPORT.txt" cmd /C notepad.exe "%~1\REPORT.txt"
	move /Y "%~1\ATTI" "%~1\ATTI_ORIGINALI" > NUL 2>&1
	IF NOT EXIST "%~1\ATTI_ORIGINALI" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\ATTI" & GOTO ERROR
	move /Y "%~1\ATTI_ORIGINALI\output\output" "%~1\ATTI" > NUL 2>&1
	IF NOT EXIST "%~1\ATTI" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\ATTI_ORIGINALI\output\output" & GOTO ERROR
	rmdir /S /Q "%~1\ATTI_ORIGINALI\output" > NUL 2>&1
	IF EXIST "%~1\ATTI_ORIGINALI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ATTI_ORIGINALI\output" & GOTO ERROR
) ELSE IF "%PRINTER_TEXT%"=="BOZZ" (
	IF EXIST "%~1\BOZZE" SET "ERROR=ESISTE GIA' LA CARTELLA %~1\BOZZE" & GOTO ERROR
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ATTI" "%PARAMS%::threads==8" "(?s)(?i).*?%SEARCH_PAGE%.*::%RECT_PAGE%" %OPS_DRAFT1% %MAYBE_LOG%
	IF EXIST "%~1\REPORT.txt" cmd /C notepad.exe "%~1\REPORT.txt"
	move /Y "%~1\ATTI\output" "%~1\BOZZE" > NUL 2>&1
	IF NOT EXIST "%~1\BOZZE" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\ATTI\output" & GOTO ERROR
) ELSE IF "%PRINTER_TEXT%"=="PREP" (
	IF EXIST "%~1\ELABORAZIONE" SET "ERROR=ESISTE GIA' LA CARTELLA %~1\ELABORAZIONE" & GOTO ERROR
	SET "SKIP_ERRORS=1"
	IF EXIST "%~1\ATTI\output" rmdir /S /Q "%~1\ATTI\output" > NUL 2>&1
	IF EXIST "%~1\ATTI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ATTI\output" & GOTO ERROR
	echo --------------------------------------------------------- %MAYBE_LOG%
	echo ------------- Elaborazione Bozze/PreStampa -------------- %MAYBE_LOG%
	echo --------------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ATTI" "%PARAMS_PREPRINT%::threads==8" "(?s)(?i).*?%SEARCH_PAGE%.*::%RECT_PAGE%" %OPS_PRINT1% %MAYBE_LOG%
	move /Y "%~1\ATTI\output" "%~1\ELABORAZIONE" > NUL 2>&1
	IF NOT EXIST "%~1\ELABORAZIONE" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\ATTI\output" & GOTO ERROR
) ELSE IF "%MULTIPLE_MODE%"=="OCTP" (
	IF EXIST "%~1\OCT" SET "ERROR=ESISTE GIA' LA CARTELLA %~1\OCT" & GOTO ERROR
	IF EXIST "%~1\ELABORAZIONE" SET "ERROR=ESISTE GIA' LA CARTELLA %~1\ELABORAZIONE" & GOTO ERROR
	rem SET "SKIP_ERRORS=1"
	IF EXIST "%~1\ATTI\output" rmdir /S /Q "%~1\ATTI\output" > NUL 2>&1
	IF EXIST "%~1\ATTI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ATTI\output" & GOTO ERROR
	echo --------------------------------------------------------- %MAYBE_LOG%
	echo ------------- Elaborazione Bozze/PreStampa -------------- %MAYBE_LOG%
	echo --------------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ATTI" "%PARAMS_PREPRINT%::threads==8" "(?s)(?i).*?%SEARCH_PAGE%.*::%RECT_PAGE%" %OPS_PRINT1% %MAYBE_LOG%

	echo ---------------------------------------------------- %MAYBE_LOG%
	echo ------------- STAMPA SU %PRINTER_TEXT% -------------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ATTI\output" "%PARAMS_PRINT%" "(?s)(?i).*?%SEARCH_PAGE%.*::%RECT_PAGE%" %OPS_PRINT2% %MAYBE_LOG%
	
	IF EXIST "%~1\REPORT.txt" cmd /C notepad.exe "%~1\REPORT.txt"
	move /Y "%~1\ATTI\output" "%~1\ELABORAZIONE" > NUL 2>&1
	IF NOT EXIST "%~1\ELABORAZIONE" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\ATTI\output" & GOTO ERROR

) ELSE IF "%CHOICE_TEXT%"=="PRINT" (
	IF NOT EXIST "%~1\ELABORAZIONE" SET "ERROR=LA CARTELLA %~1\ELABORAZIONE NON ESISTE" & GOTO ERROR
	SET "SKIP_ERRORS=1"
	IF "%PRINTER_TEXT%"=="FILE" IF EXIST "%~1\STAMPE" SET "ERROR=ESISTE GIA' LA CARTELLA %~1\STAMPE" & GOTO ERROR
	IF "%PRINTER_TEXT%"=="OCTS" IF EXIST "%~1\OCT" SET "ERROR=ESISTE GIA' LA CARTELLA %~1\OCT" & GOTO ERROR

	setlocal enabledelayedexpansion
	IF EXIST "%~1\ELABORAZIONE" echo. & choice /C RNI /M "Vuoi riprendere(R/I) da un punto specifico oppure No(N)?"
	IF EXIST "%~1\ELABORAZIONE" IF "!ERRORLEVEL!"=="3" setlocal disabledelayedexpansion & GOTO FILEFROMTOPRINT
	IF EXIST "%~1\ELABORAZIONE" IF "!ERRORLEVEL!"=="2" setlocal disabledelayedexpansion & GOTO NORECOVERYPRINT
	IF EXIST "%~1\ELABORAZIONE" IF "!ERRORLEVEL!"=="1" setlocal disabledelayedexpansion & GOTO FILEFROMPRINT
	setlocal disabledelayedexpansion

:FILEFROMPRINT
	echo.
	SET /P "FILENAME=Inserisci il nome del file da cui RIPRENDERE:"
	SET "PARAMS_PRINT=%PARAMS_PRINT%::beginFilename==%FILENAME%"
	GOTO PRINT
:FILEFROMTOPRINT
	echo.
	SET /P "FILENAME=Inserisci il nome del file da cui RIPRENDERE:"
	SET "PARAMS_PRINT=%PARAMS_PRINT%::beginFilename==%FILENAME%"
	SET /P "FILENAME=Inserisci il nome del file a cui TERMINARE:"
	SET "PARAMS_PRINT=%PARAMS_PRINT%::endFilename==%FILENAME%"
	GOTO PRINT
:NORECOVERYPRINT
:PRINT
	echo ---------------------------------------------------- %MAYBE_LOG%
	echo ------------- STAMPA SU %PRINTER_TEXT% -------------- %MAYBE_LOG%
	echo ---------------------------------------------------- %MAYBE_LOG%
	java -Xms8192m -Xmx32768m -noverify -jar "%PDFtoPDF_PATH%" "%~1\ELABORAZIONE" "%PARAMS_PRINT%" "(?s)(?i).*?%SEARCH_PAGE%.*::%RECT_PAGE%" %OPS_PRINT2% %MAYBE_LOG%
	IF "%PRINTER_TEXT%"=="FILE" move /Y "%~1\ELABORAZIONE\output" "%~1\STAMPE" > NUL 2>&1
	IF "%PRINTER_TEXT%"=="FILE" IF NOT EXIST "%~1\STAMPE" SET "ERROR=IMPOSSIBILE RINOMINARE LA CARTELLA %~1\ELABORAZIONE\output" & GOTO ERROR
:ENDPRINT
	rem IF NOT "%PRINTER_TEXT%"=="FILE" rmdir /S /Q "%~1\ATTI\output" > NUL 2>&1
	rem IF NOT "%PRINTER_TEXT%"=="FILE" IF EXIST "%~1\ATTI\output" SET "ERROR=IMPOSSIBILE ELIMINARE LA CARTELLA %~1\ATTI\output" & GOTO ERROR
)

GOTO NOERROR
:ERROR
echo.
echo %ERROR% %MAYBE_LOG%
echo E' avvenuto un errore, l'operazione potrebbe non essere andata a buon fine. %MAYBE_LOG%
echo.
:NOERROR

SET "DEL_ERRORS=0"
for %%i in ("%~1\ERRORS.txt") do IF "%%~z%i"=="0" SET "DEL_ERRORS=1"
for %%i in ("%~1\ERRORS.txt") do IF "%%~z%i"=="" SET "DEL_ERRORS=1"
rem for %%i in ("%~1\ERRORS.txt") do echo ERROR Bytes:"%%~z%i"
IF "%DEL_ERRORS%"=="1" del /A /Q /F "%~1\ERRORS.txt" > NUL 2>&1
IF NOT "%SKIP_ERRORS%"=="1" IF EXIST "%~1\ERRORS.txt" (
	echo.
	echo ATTENZIONE E' AVVENUTO UN ERRORE IMPREVISTO, CONTATTARE IL SUPPORTO TECNICO
	echo.
	cmd /C notepad.exe "%~1\ERRORS.txt"
)
del /A /Q /F %OPS_DRAFT1% > NUL 2>&1
del /A /Q /F %OPS_PRINT1% > NUL 2>&1
del /A /Q /F %OPS_PRINT2% > NUL 2>&1

echo.
echo ELABORAZIONE TERMINATA!
echo.
IF "%LOG%" NEQ "1" pause
:END
